/**
 * The merchant panel's five unbuilt views, transcribed from the design file.
 *
 * `files/MyPOS Marketplace - Do'kon paneli.dc.html` — its `t` copy object and
 * the setBreak / setBank / setActions / dspKpis / dspRules / perfKpis /
 * perfFunnel / perfStars / perfTop / perfPenalties arrays.
 *
 * The rail named nine destinations and two of them opened. A sidebar of dead
 * rows is worse than a shorter sidebar: it tells a merchant the panel is
 * unfinished at the moment they most need to trust it, which is the moment they
 * are looking for their money.
 *
 * Generated by evaluating the design's own script once per language.
 */

const uz = {
  promoBuy: [
    {
      label: 'Qidiruvda yuqorida',
      price: '180000 / kun',
      note: 'O’z oshxonangiz turkumida birinchi uchlikda',
    },
    {
      label: 'Bosh sahifa lentasi',
      price: '320000 / kun',
      note: '“Bugungi aksiyalar” lentasida',
    },
    {
      label: 'Banner',
      price: '640000 / kun',
      note: 'Bosh sahifadagi katta banner · kuniga 1 do’kon',
    },
  ],
  promoReturn: [
    {
      label: 'Qo’shimcha aylanma',
      value: '11400000',
    },
    {
      label: 'Har 1 so’mga',
      value: '5.9 so’m',
    },
    {
      label: 'Yangi mijoz',
      value: '94',
    },
  ],
  settingsGroups: [
    {
      head: 'Do’kon profili',
      note: 'Marketplace’da mijoz ko’radigan ma’lumot',
      rows: [
        {
          label: 'Nom',
          value: 'Osh Xona',
        },
        {
          label: 'Oshxona',
          value: 'O’zbek · Milliy',
        },
        {
          label: 'Rasmlar',
          value: '4 dan 12 ta',
        },
        {
          label: 'Tavsif',
          value: '184 / 240',
        },
      ],
    },
    {
      head: 'Ish vaqti',
      note: 'POS sozlamasidan keladi · bu yerda faqat marketplace uchun',
      rows: [
        {
          label: 'Dushanba–Juma',
          value: '10:00 – 23:00',
        },
        {
          label: 'Shanba–Yakshanba',
          value: '10:00 – 01:00',
        },
        {
          label: 'Oxirgi buyurtma',
          value: 'Yopilishdan 40 daqiqa oldin',
        },
        {
          label: 'Bayram kunlari',
          value: 'Alohida jadval',
        },
      ],
    },
    {
      head: 'Yetkazish',
      note: 'Kim yetkazadi va qancha turadi',
      rows: [
        {
          label: 'Kuryer',
          value: 'Platforma kuryeri',
        },
        {
          label: 'Zona',
          value: '5 km',
        },
        {
          label: 'Yetkazish narxi',
          value: '12000 so’m',
        },
        {
          label: 'Bepul yetkazish',
          value: 'O’chirilgan',
        },
      ],
    },
    {
      head: 'Shartnoma',
      note: 'Komissiya va to’lov shartlari',
      rows: [
        {
          label: 'Komissiya',
          value: '9%',
        },
        {
          label: 'To’lov davri',
          value: 'Haftalik · payshanba',
        },
        {
          label: 'Shartnoma',
          value: 'MP-2026-0412',
        },
        {
          label: 'Holat',
          value: 'Faol',
        },
      ],
    },
  ],
  text: {
    partner: 'Hamkor paneli',
    chilonzor: 'Chilonzor · Toshkent',
    secDaily: 'Kunlik ish',
    secMoney: 'Pul',
    secGrow: 'O’sish',
    navSettings: 'Sozlamalar',
    /* The drawer's hamburger, which exists only below 820px. */
    navMenu: 'Menyuni ochish',
    theme: 'Kunduzgi va tungi rejim',
    ordEmptyH: 'Bu filtrda buyurtma yo’q',
    ordEmptyP: 'Boshqa filtrni tanlang yoki barchasini ko’ring.',
    slaH: 'Nima uchun 90 soniya',
    slaP: 'Yangi buyurtma 90 soniya ichida qabul qilinmasa, mijoz kutishni to’xtatadi va buyurtma bekor qilinadi. Ikki daqiqadan uzoq kutish reytingga ta’sir qiladi — shuning uchun sanoq ko’rinib turadi.',
    catSyncH: 'Menyu POS tizimidan keladi',
    catSyncP:
      'Nom, tarkib va tugagan taomlar POS’da o’zgaradi — bu yerda faqat marketplace narxi va ko’rinishi boshqariladi. Ikki joyda menyu yuritilmaydi.',
    catSyncBtn: 'Hozir sinxronlash',
    colDish: 'Taom',
    colPosPrice: 'Zal narxi',
    colMpPrice: 'Marketplace',
    colMargin: 'Marja',
    colSold: '30 kun',
    colOn: 'Ko’rinadi',
    setNext: 'Keyingi to’lov',
    setNote:
      'To’lov har payshanba, o’tgan hafta uchun. Bank kuni bo’lmasa keyingi ish kuniga suriladi. Nizo ochiq bo’lsa, o’sha buyurtma summasi keyingi davrga o’tadi.',
    setBank: 'Bank rekvizitlari',
    setActs: 'Amallar',
    rejWarn:
      'Rad etish darajasi 3% dan oshsa qidiruvda pastga tushasiz. Oyda 2 marta rad etish me’yor ichida.',
    rejSend: 'Rad etish va mijozga xabar berish',
    rcpNote: 'Chek POS tizimida ham saqlanadi. Fiskal chek mijozga Telegram orqali yuborilgan.',
    bankName: 'Bank nomi',
    bankAcc: 'Hisob raqami',
    bankWarn:
      'Rekvizit o’zgartirilganda to’lov tasdiqlangunga qadar to’xtatiladi. Joriy hisob-kitob eski rekvizitga o’tadi.',
    bankSave: 'Tekshirishga yuborish',
    budSave: 'Byudjetni saqlash',
    cxGo: 'Ha, bekor qilish',
    cxKeep: 'Qoldirish',
    close: 'Yopish',
    setHistory: 'To’lov tarixi',
    colPeriod: 'Davr',
    colInvoice: 'Hisob-faktura',
    colGross: 'Aylanma',
    colFee: 'Komissiya',
    colNet: 'Qo’lga',
    colState: 'Holat',
    dspEmptyH: 'Ochiq nizo yo’q',
    dspEmptyP:
      'Mijoz shikoyat qilsa, u shu yerda paydo bo’ladi va javob berish uchun 24 soat bo’ladi.',
    dspAtStake: 'Bahs summasi',
    dspAccept: 'Qabul qilish',
    dspContest: 'E’tiroz bildirish',
    dspRulesH: 'Nizo qanday hal qilinadi',
    perfFunnelH: 'Ko’rildi → buyurtma',
    perfFunnelP: 'Oxirgi 30 kun',
    perfFunnelWhy:
      'Eng katta yo’qotish savatda: 41% tashlab ketadi. Sabab — yetkazish narxi savatda ko’rinadi, kartada emas. Yetkazish narxini kartada ko’rsatsangiz, yo’qotish kamayadi.',
    perfRating: 'Reyting',
    perfReviews: '· 812 baho',
    perfTop: 'Eng ko’p buyurtma',
    perfPenalty: 'Reytingga ta’sir qiladigan narsalar',
    proSpendH: 'Reklama xarajati',
    proSpendNote: 'so’m · shu oy',
    proBuyH: 'Joy sotib olish',
    proBuyNote: 'Reklama qidiruvda va lentada belgi bilan ko’rsatiladi — mijozdan yashirilmaydi.',
  },
  settlementBreakdown: [
    {
      label: 'Aylanma',
      value: '24180000',
    },
    {
      label: 'Komissiya 9%',
      value: '−2176200',
    },
    {
      label: 'Nizo bo’yicha ushlangan',
      value: '−24000',
    },
    {
      label: 'Reklama',
      value: '−480000',
    },
    {
      label: 'Qo’lga',
      value: '21499800',
    },
  ],
  bank: [
    {
      label: 'Bank',
      value: 'Kapitalbank',
    },
    {
      label: 'Hisob',
      value: '2020 8000 4471 9012',
    },
    {
      label: 'INN',
      value: '302 481 776',
    },
    {
      label: 'Holat',
      value: 'Tasdiqlangan',
    },
  ],
  settlementActions: [
    {
      label: 'Hisob-fakturani yuklash',
    },
    {
      label: 'Aktni yuklash',
    },
    {
      label: 'Rekvizitni o’zgartirish',
    },
  ],
  disputeKpis: [
    {
      label: 'Ochiq nizo',
      value: '0',
      note: 'javob kutmoqda',
    },
    {
      label: '30 kunda',
      value: '7',
      note: '1 042 buyurtmadan',
    },
    {
      label: 'Nizo darajasi',
      value: '0.67%',
      note: 'me’yor 1% dan kam',
    },
    {
      label: 'Ushlangan summa',
      value: '184000',
      note: 'so’m · shu oy',
    },
  ],
  disputeRules: [
    {
      label: 'Javob bermasangiz, 24 soatdan keyin nizo mijoz foydasiga hal qilinadi.',
    },
    {
      label: 'Qabul qilsangiz, summa keyingi to’lovdan ushlanadi va komissiya qaytariladi.',
    },
    {
      label:
        'E’tiroz bildirsangiz, platforma 48 soatda qaror qabul qiladi. Dalil sifatida oshxona cheki va tayyorlash vaqti ishlatiladi.',
    },
    {
      label: 'Nizo darajasi 3% dan oshsa, do’kon qidiruvda pastga tushadi.',
    },
  ],
  performance: [
    {
      label: 'Buyurtma',
      value: '1 042',
      note: 'o’tgan oyga nisbatan +18%',
    },
    {
      label: 'O’rtacha chek',
      value: '96 000',
      note: 'marketplace o’rtachasi 84 000',
    },
    {
      label: 'Tayyorlash vaqti',
      value: '23 daq',
      note: 'va’da qilingan 25 daqiqa',
    },
    {
      label: 'Bekor qilish',
      value: '1.9%',
      note: 'me’yor 3% dan kam',
    },
  ],
  funnel: [
    {
      label: 'Ko’rildi',
      value: '18 420',
      drop: '',
    },
    {
      label: 'Do’kon ochildi',
      value: '6 840',
      drop: '−63%',
    },
    {
      label: 'Savatga qo’shildi',
      value: '1 762',
      drop: '−74%',
    },
    {
      label: 'Buyurtma berildi',
      value: '1 042',
      drop: '−41%',
    },
  ],
  stars: [
    {
      star: '5',
      count: '634',
    },
    {
      star: '4',
      count: '114',
    },
    {
      star: '3',
      count: '41',
    },
    {
      star: '2',
      count: '16',
    },
    {
      star: '1',
      count: '7',
    },
  ],
  topDishes: [
    {
      name: 'Osh, to’y oshi',
      count: '412',
    },
    {
      name: 'Kola, 0.5',
      count: '502',
    },
    {
      name: 'Ko’k choy',
      count: '388',
    },
    {
      name: 'Achchiq lag’mon',
      count: '268',
    },
    {
      name: 'Margherita, 30 sm',
      count: '226',
    },
  ],
  penalties: [
    {
      head: '90 soniyada javob berish',
      body: 'O’rtacha 38 soniya — me’yor ichida',
      value: '38 son',
    },
    {
      head: 'Tayyorlash vaqtiga rioya',
      body: '94% buyurtma va’da qilingan vaqtda tayyor bo’lgan',
      value: '94%',
    },
    {
      head: 'Bekor qilish darajasi',
      body: 'Do’kon tomonidan bekor qilingan buyurtmalar',
      value: '1.9%',
    },
    {
      head: 'Nizo darajasi',
      body: '3% dan oshsa qidiruvda pastga tushasiz',
      value: '0.67%',
    },
  ],
};

/** The shape every language fills. */
export type MerchantCopy = typeof uz;

const ru: MerchantCopy = {
  promoBuy: [
    {
      label: 'Верх поиска',
      price: '180000 / день',
      note: 'В тройке первых в своей кухне',
    },
    {
      label: 'Лента на главной',
      price: '320000 / день',
      note: 'В ленте “Акции сегодня”',
    },
    {
      label: 'Баннер',
      price: '640000 / день',
      note: 'Большой баннер на главной · 1 магазин в день',
    },
  ],
  promoReturn: [
    {
      label: 'Доп. оборот',
      value: '11400000',
    },
    {
      label: 'На 1 сум',
      value: '5.9 so’m',
    },
    {
      label: 'Новых гостей',
      value: '94',
    },
  ],
  settingsGroups: [
    {
      head: 'Профиль магазина',
      note: 'Что гость видит на маркетплейсе',
      rows: [
        {
          label: 'Название',
          value: 'Osh Xona',
        },
        {
          label: 'Кухня',
          value: 'Узбекская · Национальная',
        },
        {
          label: 'Фотографии',
          value: '4 из 12',
        },
        {
          label: 'Описание',
          value: '184 / 240',
        },
      ],
    },
    {
      head: 'Часы работы',
      note: 'Приходит из настроек POS · здесь только для маркетплейса',
      rows: [
        {
          label: 'Пн–Пт',
          value: '10:00 – 23:00',
        },
        {
          label: 'Сб–Вс',
          value: '10:00 – 01:00',
        },
        {
          label: 'Последний заказ',
          value: 'За 40 минут до закрытия',
        },
        {
          label: 'Праздники',
          value: 'Отдельный график',
        },
      ],
    },
    {
      head: 'Доставка',
      note: 'Кто доставляет и сколько стоит',
      rows: [
        {
          label: 'Курьер',
          value: 'Курьер платформы',
        },
        {
          label: 'Зона',
          value: '5 km',
        },
        {
          label: 'Стоимость доставки',
          value: '12000 so’m',
        },
        {
          label: 'Бесплатная доставка',
          value: 'Выключено',
        },
      ],
    },
    {
      head: 'Договор',
      note: 'Комиссия и условия выплат',
      rows: [
        {
          label: 'Комиссия',
          value: '9%',
        },
        {
          label: 'Период выплат',
          value: 'Недельно · четверг',
        },
        {
          label: 'Договор',
          value: 'MP-2026-0412',
        },
        {
          label: 'Статус',
          value: 'Активен',
        },
      ],
    },
  ],
  text: {
    partner: 'Панель партнёра',
    chilonzor: 'Чиланзар · Ташкент',
    secDaily: 'Ежедневно',
    secMoney: 'Деньги',
    secGrow: 'Рост',
    navSettings: 'Настройки',
    navMenu: 'Открыть меню',
    theme: 'Светлая и тёмная тема',
    ordEmptyH: 'В этом фильтре заказов нет',
    ordEmptyP: 'Выберите другой фильтр или посмотрите все.',
    slaH: 'Почему 90 секунд',
    slaP: 'Если новый заказ не принят за 90 секунд, гость перестаёт ждать и заказ отменяется. Ожидание дольше двух минут влияет на рейтинг — поэтому счётчик виден.',
    catSyncH: 'Меню приходит из POS',
    catSyncP:
      'Название, состав и стоп-лист меняются в POS — здесь управляется только цена и видимость на маркетплейсе. Меню не ведётся в двух местах.',
    catSyncBtn: 'Синхронизировать',
    colDish: 'Блюдо',
    colPosPrice: 'Цена в зале',
    colMpPrice: 'Маркетплейс',
    colMargin: 'Маржа',
    colSold: '30 дней',
    colOn: 'Видно',
    setNext: 'Следующая выплата',
    setNote:
      'Выплата каждый четверг за прошлую неделю. Если день нерабочий — переносится. При открытом споре сумма заказа переходит в следующий период.',
    setBank: 'Банковские реквизиты',
    setActs: 'Действия',
    rejWarn:
      'Если доля отклонений превысит 3%, вы опуститесь в поиске. Два отклонения в месяц — в норме.',
    rejSend: 'Отклонить и уведомить гостя',
    rcpNote: 'Чек также хранится в POS. Фискальный чек отправлен гостю в Telegram.',
    bankName: 'Название банка',
    bankAcc: 'Номер счёта',
    bankWarn:
      'При смене реквизитов выплаты приостанавливаются до подтверждения. Текущий расчёт уйдёт на старые реквизиты.',
    bankSave: 'Отправить на проверку',
    budSave: 'Сохранить бюджет',
    cxGo: 'Да, отменить',
    cxKeep: 'Оставить',
    close: 'Закрыть',
    setHistory: 'История выплат',
    colPeriod: 'Период',
    colInvoice: 'Счёт',
    colGross: 'Оборот',
    colFee: 'Комиссия',
    colNet: 'К выплате',
    colState: 'Статус',
    dspEmptyH: 'Открытых споров нет',
    dspEmptyP: 'Если гость жалуется, обращение появится здесь; на ответ есть 24 часа.',
    dspAtStake: 'Сумма спора',
    dspAccept: 'Признать',
    dspContest: 'Оспорить',
    dspRulesH: 'Как решается спор',
    perfFunnelH: 'Просмотры → заказ',
    perfFunnelP: 'Последние 30 дней',
    perfFunnelWhy:
      'Основная потеря в корзине: 41% уходит. Причина — стоимость доставки видна только в корзине. Покажите её на карточке, и потеря снизится.',
    perfRating: 'Рейтинг',
    perfReviews: '· 812 оценок',
    perfTop: 'Чаще всего заказывают',
    perfPenalty: 'Что влияет на рейтинг',
    proSpendH: 'Расходы на рекламу',
    proSpendNote: 'сум · этот месяц',
    proBuyH: 'Купить размещение',
    proBuyNote: 'Реклама в поиске и в лентах помечается — от гостя не скрывается.',
  },
  settlementBreakdown: [
    {
      label: 'Оборот',
      value: '24180000',
    },
    {
      label: 'Комиссия 9%',
      value: '−2176200',
    },
    {
      label: 'Удержано по спорам',
      value: '−24000',
    },
    {
      label: 'Реклама',
      value: '−480000',
    },
    {
      label: 'К выплате',
      value: '21499800',
    },
  ],
  bank: [
    {
      label: 'Банк',
      value: 'Kapitalbank',
    },
    {
      label: 'Счёт',
      value: '2020 8000 4471 9012',
    },
    {
      label: 'INN',
      value: '302 481 776',
    },
    {
      label: 'Статус',
      value: 'Подтверждён',
    },
  ],
  settlementActions: [
    {
      label: 'Скачать счёт',
    },
    {
      label: 'Скачать акт',
    },
    {
      label: 'Изменить реквизиты',
    },
  ],
  disputeKpis: [
    {
      label: 'Открытых споров',
      value: '0',
      note: 'ждут ответа',
    },
    {
      label: 'За 30 дней',
      value: '7',
      note: 'из 1 042 заказов',
    },
    {
      label: 'Доля споров',
      value: '0.67%',
      note: 'норма ниже 1%',
    },
    {
      label: 'Удержано',
      value: '184000',
      note: 'so’m · этот месяц',
    },
  ],
  disputeRules: [
    {
      label: 'Без ответа через 24 часа спор решается в пользу гостя.',
    },
    {
      label: 'При признании сумма удерживается из следующей выплаты, комиссия возвращается.',
    },
    {
      label:
        'При возражении платформа решает за 48 часов. Как доказательство используются кухонный чек и время приготовления.',
    },
    {
      label: 'Если доля споров выше 3%, магазин опускается в поиске.',
    },
  ],
  performance: [
    {
      label: 'Заказов',
      value: '1 042',
      note: 'к прошлому месяцу +18%',
    },
    {
      label: 'Средний чек',
      value: '96 000',
      note: 'средний по маркетплейсу 84 000',
    },
    {
      label: 'Время приготовления',
      value: '23 мин',
      note: 'обещано 25 минут',
    },
    {
      label: 'Отмены',
      value: '1.9%',
      note: 'норма ниже 3%',
    },
  ],
  funnel: [
    {
      label: 'Просмотры',
      value: '18 420',
      drop: '',
    },
    {
      label: 'Открыли магазин',
      value: '6 840',
      drop: '−63%',
    },
    {
      label: 'Добавили в корзину',
      value: '1 762',
      drop: '−74%',
    },
    {
      label: 'Оформили заказ',
      value: '1 042',
      drop: '−41%',
    },
  ],
  stars: [
    {
      star: '5',
      count: '634',
    },
    {
      star: '4',
      count: '114',
    },
    {
      star: '3',
      count: '41',
    },
    {
      star: '2',
      count: '16',
    },
    {
      star: '1',
      count: '7',
    },
  ],
  topDishes: [
    {
      name: 'Плов свадебный',
      count: '412',
    },
    {
      name: 'Кола 0.5',
      count: '502',
    },
    {
      name: 'Зелёный чай',
      count: '388',
    },
    {
      name: 'Острый лагман',
      count: '268',
    },
    {
      name: 'Маргарита 30 см',
      count: '226',
    },
  ],
  penalties: [
    {
      head: 'Ответ за 90 секунд',
      body: 'В среднем 38 секунд — в норме',
      value: '38 сек',
    },
    {
      head: 'Соблюдение времени',
      body: '94% заказов готовы к обещанному времени',
      value: '94%',
    },
    {
      head: 'Доля отмен',
      body: 'Заказы, отменённые магазином',
      value: '1.9%',
    },
    {
      head: 'Доля споров',
      body: 'Выше 3% — понижение в поиске',
      value: '0.67%',
    },
  ],
};

const en: MerchantCopy = {
  promoBuy: [
    {
      label: 'Top of search',
      price: '180000 / day',
      note: 'In the first three of your cuisine',
    },
    {
      label: 'Home rail',
      price: '320000 / day',
      note: 'In the “Today’s offers” rail',
    },
    {
      label: 'Banner',
      price: '640000 / day',
      note: 'The large home banner · one store a day',
    },
  ],
  promoReturn: [
    {
      label: 'Extra gross',
      value: '11400000',
    },
    {
      label: 'Per 1 so’m',
      value: '5.9 so’m',
    },
    {
      label: 'New guests',
      value: '94',
    },
  ],
  settingsGroups: [
    {
      head: 'Store profile',
      note: 'What the guest sees on the marketplace',
      rows: [
        {
          label: 'Name',
          value: 'Osh Xona',
        },
        {
          label: 'Cuisine',
          value: 'Uzbek · National',
        },
        {
          label: 'Photos',
          value: '4 of 12',
        },
        {
          label: 'Description',
          value: '184 / 240',
        },
      ],
    },
    {
      head: 'Opening hours',
      note: 'Comes from the POS · here only for the marketplace',
      rows: [
        {
          label: 'Mon–Fri',
          value: '10:00 – 23:00',
        },
        {
          label: 'Sat–Sun',
          value: '10:00 – 01:00',
        },
        {
          label: 'Last order',
          value: '40 minutes before closing',
        },
        {
          label: 'Holidays',
          value: 'Separate schedule',
        },
      ],
    },
    {
      head: 'Delivery',
      note: 'Who delivers and what it costs',
      rows: [
        {
          label: 'Courier',
          value: 'Platform courier',
        },
        {
          label: 'Zone',
          value: '5 km',
        },
        {
          label: 'Delivery fee',
          value: '12000 so’m',
        },
        {
          label: 'Free delivery',
          value: 'Off',
        },
      ],
    },
    {
      head: 'Contract',
      note: 'Commission and payout terms',
      rows: [
        {
          label: 'Commission',
          value: '9%',
        },
        {
          label: 'Payout period',
          value: 'Weekly · Thursday',
        },
        {
          label: 'Agreement',
          value: 'MP-2026-0412',
        },
        {
          label: 'State',
          value: 'Active',
        },
      ],
    },
  ],
  text: {
    partner: 'Partner panel',
    chilonzor: 'Chilonzor · Tashkent',
    secDaily: 'Daily',
    secMoney: 'Money',
    secGrow: 'Growth',
    navSettings: 'Settings',
    navMenu: 'Open the menu',
    theme: 'Light and dark theme',
    ordEmptyH: 'No orders in this filter',
    ordEmptyP: 'Pick another filter, or view all.',
    slaH: 'Why 90 seconds',
    slaP: 'If a new order is not accepted within 90 seconds the guest stops waiting and the order cancels. Waits over two minutes affect the rating — which is why the countdown is visible.',
    catSyncH: 'The menu comes from the POS',
    catSyncP:
      'Names, recipes and the stop-list change in the POS — here you control only the marketplace price and visibility. The menu is never maintained twice.',
    catSyncBtn: 'Sync now',
    colDish: 'Dish',
    colPosPrice: 'In-house',
    colMpPrice: 'Marketplace',
    colMargin: 'Margin',
    colSold: '30 days',
    colOn: 'Visible',
    setNext: 'Next payout',
    setNote:
      'Payouts run every Thursday for the previous week. Non-banking days shift to the next working day. An open dispute moves that order’s amount to the next period.',
    setBank: 'Bank details',
    setActs: 'Actions',
    rejWarn:
      'Above a 3% rejection rate you drop in search. Two rejections a month is within target.',
    rejSend: 'Reject and tell the guest',
    rcpNote:
      'The receipt is also kept in the POS. The fiscal receipt went to the guest on Telegram.',
    bankName: 'Bank name',
    bankAcc: 'Account number',
    bankWarn:
      'Payouts pause until the change is verified. The current settlement goes to the old account.',
    bankSave: 'Submit for verification',
    budSave: 'Save the budget',
    cxGo: 'Yes, cancel it',
    cxKeep: 'Keep it',
    close: 'Close',
    setHistory: 'Payout history',
    colPeriod: 'Period',
    colInvoice: 'Invoice',
    colGross: 'Gross',
    colFee: 'Fee',
    colNet: 'Net',
    colState: 'State',
    dspEmptyH: 'No open disputes',
    dspEmptyP: 'When a guest complains it appears here, and you have 24 hours to respond.',
    dspAtStake: 'At stake',
    dspAccept: 'Accept',
    dspContest: 'Contest',
    dspRulesH: 'How a dispute is settled',
    perfFunnelH: 'Views → order',
    perfFunnelP: 'Last 30 days',
    perfFunnelWhy:
      'The biggest loss is in the cart: 41% leave. The cause is that the delivery fee appears only in the cart. Show it on the card and the loss falls.',
    perfRating: 'Rating',
    perfReviews: '· 812 ratings',
    perfTop: 'Ordered most',
    perfPenalty: 'What affects the rating',
    proSpendH: 'Ad spend',
    proSpendNote: 'so’m · this month',
    proBuyH: 'Buy placement',
    proBuyNote:
      'Promoted placements are labelled in search and in the rails — never hidden from the guest.',
  },
  settlementBreakdown: [
    {
      label: 'Gross',
      value: '24180000',
    },
    {
      label: 'Commission 9%',
      value: '−2176200',
    },
    {
      label: 'Withheld for disputes',
      value: '−24000',
    },
    {
      label: 'Advertising',
      value: '−480000',
    },
    {
      label: 'You receive',
      value: '21499800',
    },
  ],
  bank: [
    {
      label: 'Bank',
      value: 'Kapitalbank',
    },
    {
      label: 'Account',
      value: '2020 8000 4471 9012',
    },
    {
      label: 'INN',
      value: '302 481 776',
    },
    {
      label: 'State',
      value: 'Verified',
    },
  ],
  settlementActions: [
    {
      label: 'Download invoice',
    },
    {
      label: 'Download statement',
    },
    {
      label: 'Change bank details',
    },
  ],
  disputeKpis: [
    {
      label: 'Open disputes',
      value: '0',
      note: 'awaiting you',
    },
    {
      label: 'Last 30 days',
      value: '7',
      note: 'of 1 042 orders',
    },
    {
      label: 'Dispute rate',
      value: '0.67%',
      note: 'target under 1%',
    },
    {
      label: 'Withheld',
      value: '184000',
      note: 'so’m · this month',
    },
  ],
  disputeRules: [
    {
      label: 'With no answer, after 24 hours the dispute is settled for the guest.',
    },
    {
      label:
        'If you accept, the amount is withheld from the next payout and the commission is reversed.',
    },
    {
      label:
        'If you contest, the platform decides within 48 hours, using the kitchen ticket and the prep time as evidence.',
    },
    {
      label: 'A dispute rate above 3% pushes the store down in search.',
    },
  ],
  performance: [
    {
      label: 'Orders',
      value: '1 042',
      note: '+18% vs last month',
    },
    {
      label: 'Average ticket',
      value: '96 000',
      note: 'marketplace average 84 000',
    },
    {
      label: 'Prep time',
      value: '23 min',
      note: '25 minutes promised',
    },
    {
      label: 'Cancellations',
      value: '1.9%',
      note: 'target under 3%',
    },
  ],
  funnel: [
    {
      label: 'Impressions',
      value: '18 420',
      drop: '',
    },
    {
      label: 'Store opened',
      value: '6 840',
      drop: '−63%',
    },
    {
      label: 'Added to cart',
      value: '1 762',
      drop: '−74%',
    },
    {
      label: 'Ordered',
      value: '1 042',
      drop: '−41%',
    },
  ],
  stars: [
    {
      star: '5',
      count: '634',
    },
    {
      star: '4',
      count: '114',
    },
    {
      star: '3',
      count: '41',
    },
    {
      star: '2',
      count: '16',
    },
    {
      star: '1',
      count: '7',
    },
  ],
  topDishes: [
    {
      name: 'Plov, wedding style',
      count: '412',
    },
    {
      name: 'Cola 0.5',
      count: '502',
    },
    {
      name: 'Green tea',
      count: '388',
    },
    {
      name: 'Spicy lagman',
      count: '268',
    },
    {
      name: 'Margherita 30 cm',
      count: '226',
    },
  ],
  penalties: [
    {
      head: 'Answer within 90 seconds',
      body: '38 seconds on average — within target',
      value: '38 s',
    },
    {
      head: 'Prep time kept',
      body: '94% of orders were ready on time',
      value: '94%',
    },
    {
      head: 'Cancellation rate',
      body: 'Orders cancelled by the store',
      value: '1.9%',
    },
    {
      head: 'Dispute rate',
      body: 'Above 3% you drop in search',
      value: '0.67%',
    },
  ],
};

const COPY = { uz, ru, en } as const;

export function merchantCopy(lang: 'uz' | 'ru' | 'en'): MerchantCopy {
  return COPY[lang] ?? uz;
}
