/**
 * The staff app's sub-screens, transcribed from the design file.
 *
 * `files/Smart Restaurant Xodimlar ilovasi.dc.html` — its `mf` copy object and
 * the PNL / PEOPLE / RISK / CLOSE / ROTA / STA / WREASONS / WITEMS / EXP /
 * PITEMS / SWSH / SWWHO / HBR / BR arrays, in the order it declares them.
 *
 * Seventeen screens hung off the More menu in that file and every one of them
 * was a `built: false` row here — a list of names a manager could read and not
 * open. This is their words; `more-data.ts` is their structure.
 *
 * Generated by evaluating the design's own script once per language, so the
 * three cannot drift in transcription and nothing below is a paraphrase.
 */

const uz = {
  endShift: [
    {
      label: 'Barcha buyurtmalar yopilgan',
      note: '{n} ta qolgan',
    },
    {
      label: 'Naqd kassaga topshirilgan',
      note: '148 000 so’m kutilmoqda',
    },
    {
      label: 'Moped qaytarilgan',
      note: 'Kalit va akkumulyator',
    },
    {
      label: 'Termosumka tozalangan',
      note: 'Har smena oxirida majburiy',
    },
  ],
  shift: {
    sales: '1 840 000',
    salesNote: 'so’m · 18 chek · smena rejasi 2.1 mln',
    kpis: [
      {
        label: 'Cheklar',
        value: '18',
        note: '6 stol',
      },
      {
        label: 'O’rtacha chek',
        value: '102 000',
        note: '+8.4%',
      },
      {
        label: 'Choypuli',
        value: '84 000',
        note: 'kartadan',
      },
      {
        label: 'Soat',
        value: '6.4',
        note: '12:00 dan',
      },
    ],
    top: [
      {
        name: 'Osh, to’y oshi',
        quantity: '12',
      },
      {
        name: 'Chizburger',
        quantity: '9',
      },
      {
        name: 'Tovuqli lavash',
        quantity: '7',
      },
      {
        name: 'Ko’k choy',
        quantity: '22',
      },
    ],
  },
  bookings: [
    {
      name: 'Alisher Karimov',
      time: '19:30',
      meta: 'Stol 19 · 4 mehmon · telefon orqali',
      note: 'Tug’ilgan kun · tort olib kelishadi',
    },
    {
      name: 'Malika Yo’ldosheva',
      time: '20:00',
      meta: 'Stol 12 · 2 mehmon · Telegram',
      note: '',
    },
    {
      name: 'Sardor Toshmatov',
      time: '20:30',
      meta: 'Stol 14 · 6 mehmon · sayt',
      note: 'Tasdiqlanmagan · qo’ng’iroq qilish kerak',
    },
    {
      name: 'Nodira Umarova',
      time: '21:00',
      meta: 'Stol 7 · 3 mehmon · telefon orqali',
      note: '',
    },
  ],
  day: {
    earned: '96 000',
    earnedNote: 'so’m · 8 yetkazish · 34 km',
    kpis: [
      {
        label: 'Yetkazishlar',
        value: '8',
        note: '2 tasi navbatda',
      },
      {
        label: 'O’rtacha vaqt',
        value: '24 daq',
        note: 'me’yor 30 daq',
      },
      {
        label: 'Masofa',
        value: '34 km',
        note: 'moped',
      },
      {
        label: 'Reyting',
        value: '4.8',
        note: '6 baho',
      },
    ],
    log: [
      {
        address: 'Bunyodkor 12, 3-podyezd',
        meta: '11:42 · 18 daq',
        amount: '12 000',
      },
      {
        address: 'Chilonzor 9-kvartal, 4-uy',
        meta: '12:20 · 26 daq',
        amount: '12 000',
      },
      {
        address: 'Katta Xalqa yo’li 41',
        meta: '13:05 · 31 daq',
        amount: '14 000',
      },
      {
        address: 'Lutfiy 28, ofis 2',
        meta: '14:10 · 22 daq',
        amount: '12 000',
      },
      {
        address: 'Novza metro, 5-uy',
        meta: '15:02 · 19 daq',
        amount: '12 000',
      },
    ],
  },
  text: {
    rOwn: 'Egasi',
    rMgr: 'Menejer',
    rWh: 'Ombor',
    rWa: 'Ofitsiant',
    rCo: 'Kuryer',
    tab2BadgeN: '[object Object]',
    tab3BadgeN: '[object Object]',
    revLbl: 'Bugungi tushum · 5 filial',
    rev: '18 420 000',
    revDelta: '+12.4%',
    revNote: 'so’m · QQS bilan · 11:24 holatiga',
    listLbl: 'Filiallar',
    brIntro:
      'Kunlik rejaga nisbatan bajarilish chizig’i bilan. Yashil — reja bajarilgan, ko’k — 85% dan yuqori, sariq — orqada.',
    brOrders: 'Buyurtma',
    brMargin: 'Marja',
    brStaff: 'Xodim',
    apprIntro:
      'Xodim so’rov yuborganda telefoningizga bildirishnoma keladi. Restoranda bo’lishingiz shart emas.',
    apprYes: 'Tasdiqlash',
    apprNo: 'Rad etish',
    apprEmpty: 'Kutayotgan so’rov yo’q',
    scan: 'Shtrix-kodni skanerlash',
    recvToday: 'Bugungi yetkazishlar',
    recvAccept: 'Qabul qilishni boshlash',
    countIntro:
      'Tizimdagi son ataylab ko’rsatilmaydi — avval sanang, farqni tizim o’zi hisoblaydi.',
    countSave: 'Sanoqni saqlash',
    countNote:
      'Saqlangandan keyin o’zgartirib bo’lmaydi. Farq 5% dan oshsa, menejer tasdig’i so’raladi.',
    profileLbl: 'Akkaunt',
    menuSearch: 'Taomni qidirish…',
    menuNone: 'Bu nom bo’yicha taom topilmadi',
    billAdd: 'Qo’shish',
    billEmpty: 'Bu hisob hozircha bo’sh. «Qo’shish» bilan taom qo’shing.',
    billTotal: 'Jami',
    billSync: 'Yangilash',
    dishNote: 'Oshpazga izoh',
    dishNotePh: 'Masalan: achchiq qo’shmang',
    hrsThis: 'Joriy hafta',
    hrsNote:
      'Soat kirish va chiqish vaqtidan hisoblanadi. Tanaffus avtomatik ayirilmaydi — menejer qo’lda kiritadi.',
    acctAdd: 'Hisob qo’shish',
    myOpen: 'Mening ochiq stollarim',
    newOrder: 'Yangi buyurtma',
    zonesNote:
      'Zal tanlangandan keyin faqat o’sha zalning stollari ko’rinadi. Bo’sh stol soni jonli yangilanadi.',
    searchLbl: 'Qidirish',
    back: 'Orqaga',
    pinH: 'Smena boshlanishi',
    pinBranch: 'Chilonzor filiali · POS-3',
    pinDemo: 'Namoyish uchun PIN kodlar',
    vPin: 'PIN kirish',
    vLock: 'Qulflangan ekran',
    vApp: 'Ilova',
    stageNote: 'PIN rolni aniqlaydi · qulflangan ekran rolga qarab o’zgaradi',
    lockDate: 'Seshanba, 11-avgust',
    lockNote:
      'Bildirishnoma turi rolga qarab o’zgaradi. Tasdiq so’rovi va yangi buyurtma qulfni ochmasdan javob berish imkonini beradi.',
    qEmpty: 'Navbat bo’sh. Oflayn rejimda bajarilgan amallar shu yerda to’planadi.',
    qNote:
      'Navbatdagi amallar takroriy yuborilmaydi — har biriga bir martalik kalit beriladi. Kalit tizim tomonidan tekshiriladi.',
    ordVatNote: 'Narx ichida QQS 12% bor. Xizmat haqi olib ketish va yetkazishda olinmaydi.',
    tdLines: 'Buyurtma tarkibi',
    tdTotal: 'Jami',
    bdRev: 'Bugungi tushum',
    bdHours: 'Soat bo’yicha buyurtmalar',
    scanHint: 'Kod avtomatik o’qiladi. Qo’lda kiritish uchun ekranni bosib turing.',
    scanSim: 'Namoyish: keyingi kodni o’qish',
    scanFound: 'O’qilgan pozitsiyalar',
    scanSave: 'Qabulni yakunlash',
    scanNote:
      'Hujjatdagi miqdor bilan farq chiqsa, tizim o’zi ogohlantiradi va menejerga xabar yuboradi.',
    hbSend: 'Operatorga yuborish',
    hbNote:
      'Buyurtma boshqa kuryerga o’tadi. Sabab jurnalga yoziladi va reytingingizga ta’sir qilmaydi.',
    endCta: 'Smenani yopish',
    endNote:
      'Smena yopilgandan keyin yangi buyurtma kelmaydi. Daromad oy oxirida maosh bilan beriladi.',
    swapMine: 'Mening smenalarim',
    swapWho: 'Kim bilan',
    swapSend: 'So’rov yuborish',
    swapNote: 'Almashtirish ikki tomon va menejer tasdiqlagandan keyin kuchga kiradi.',
    pnlNote:
      'Tushum QQS’siz ko’rsatilgan. Kassa aylanmasi QQS bilan 18.4 mln — ikkisi aralashtirilmaydi.',
    cashFlowLbl: 'Naqd oqim, oxirgi 6 oy',
    riskLbl: 'Xodimlar bo’yicha xavf',
    riskNote:
      'Xavf ballari — bu ayblov emas, tekshirish uchun ishora. Har bir holatni odam ko’rib chiqishi kerak.',
    closeDo: 'Bajarish',
    closeCta: 'Smenani yopish',
    closeNote:
      'Smena yopilgandan keyin bu kunning cheklarini o’zgartirib bo’lmaydi. Z-hisobot fiskal modulga yoziladi.',
    rotaNote: 'Kechikish va kelmaslik avtomatik qayd etiladi va oylik hisobga tushadi.',
    stationNote:
      'Me’yordan oshgan bo’lim qizil ko’rsatiladi. Grill bugun 2.2 daqiqa orqada — bitta oshpaz yetmayapti.',
    wasteTotal: 'Jami zarar',
    wasteSave: 'Chiqindini qayd etish',
    wasteNote:
      'Qayd etilgandan keyin ombordan avtomatik yechiladi va tannarxga kiradi. Bekor qilish uchun menejer tasdig’i kerak.',
    expiryNote:
      'Muddati ikki kundan kam qolgan mahsulot qizil. Ular birinchi navbatda ishlatilishi kerak.',
    porderTotal: 'Buyurtma summasi',
    porderSend: 'Yetkazib beruvchiga yuborish',
    porderSupplier: 'Yetkazib beruvchi',
    porderNote:
      'Yuborilgandan keyin buyurtma xarid buyurtmalari ro’yxatiga tushadi va menejer ko’radi.',
    shiftSales: 'Smena savdosi',
    shiftTop: 'Mening eng ko’p sotganlarim',
    shiftNote: 'Choypuli oy oxirida maosh bilan beriladi. Naqd choypuli tizimga kiritilmaydi.',
    bookNote: 'Tasdiqlanmagan bandlov sariq bilan belgilangan — mijozga qo’ng’iroq qilish kerak.',
    dayEarn: 'Bugungi daromadim',
    dayLog: 'Bugungi yetkazishlar',
    dayNote:
      'Daromad har yetkazish uchun belgilangan to’lov va masofaga qarab hisoblanadi. Choypuli alohida.',
    openPos: 'Buyurtma qabul qilish',
    callsEmpty: 'Chaqiruv yo’q',
    menuIntro: 'Tugagan taomlar xira ko’rsatilgan — mijozga taklif qilmang.',
    soldOut: 'Tugadi',
    coPick: 'Olib ketdim',
    coDrop: 'Yetkazdim',
    rtTotal: 'Qolgan masofa',
    rtKm: '12.8 km',
    rtTime: 'Taxminiy vaqt',
    rtMins: '38 daq',
    rtNote:
      'Tartib eng qisqa yo’l bo’yicha tuzilgan. Yangi buyurtma qo’shilsa, yo’nalish o’zi qayta tuziladi.',
    cashOnMe: 'Qo’lingizdagi naqd',
    cashTotal: '148 000',
    cashNote: 'so’m · 2 buyurtma · smena boshidan',
    cashRows: 'Yig’ilgan naqd',
    cashHand: 'Kassirga topshirish',
    cashHandNote:
      'Topshirgandan keyin kassir sanaydi va tasdiqlaydi. Tasdiqlanmaguncha summa sizning hisobingizda qoladi.',
    moreNote:
      'Bu ilova kompyuterdagi tizimning o’rnini bosmaydi. U faqat restoranda bo’lmaganda kerak bo’ladigan ishlarni bajaradi.',
  },
  pnl: [
    {
      label: 'Tushum, QQS’siz',
      value: '16 446 000',
    },
    {
      label: 'Mahsulot tannarxi',
      value: '−6 184 000',
    },
    {
      label: 'Yalpi foyda',
      value: '10 262 000',
    },
    {
      label: 'Mehnat xarajati',
      value: '−3 620 000',
    },
    {
      label: 'Ijara va kommunal',
      value: '−1 480 000',
    },
    {
      label: 'Boshqa xarajatlar',
      value: '−1 080 000',
    },
    {
      label: 'Sof foyda',
      value: '4 082 000',
    },
  ],
  people: [
    {
      initials: 'JT',
      name: 'Jasur Toshev',
      role: 'Ofitsiant · Chilonzor',
      sales: '1.84 mln',
      meta: '18 chek',
    },
    {
      initials: 'DN',
      name: 'Dilshod Nazarov',
      role: 'Ofitsiant · Chilonzor',
      sales: '1.52 mln',
      meta: '16 chek',
    },
    {
      initials: 'NS',
      name: 'Nilufar Saidova',
      role: 'Kassir · Chilonzor',
      sales: '1.31 mln',
      meta: '14 chek',
    },
    {
      initials: 'KY',
      name: 'Kamola Yusupova',
      role: 'Ofitsiant · Yunusobod',
      sales: '1.08 mln',
      meta: '12 chek',
    },
    {
      initials: 'AR',
      name: 'Aziza Rahimova',
      role: 'Menejer · Chilonzor',
      sales: '—',
      meta: 'smenada',
    },
    {
      initials: 'BI',
      name: 'Bekzod Ismoilov',
      role: 'Omborchi · Chilonzor',
      sales: '—',
      meta: 'smenada',
    },
  ],
  risk: [
    {
      name: 'Jasur Toshev',
      score: '78',
      meta: '6 bekor qilish · 4 o’chirish · 340 000 chegirma',
    },
    {
      name: 'Nilufar Saidova',
      score: '52',
      meta: '2 qaytarish · kassa farqi 32 000',
    },
    {
      name: 'Dilshod Nazarov',
      score: '24',
      meta: '1 bekor qilish · chegirma yo’q',
    },
    {
      name: 'Kamola Yusupova',
      score: '11',
      meta: 'Hech qanday belgi yo’q',
    },
  ],
  closing: [
    {
      label: 'Barcha stollar yopilgan',
      note: '32 stoldan 32 tasi',
    },
    {
      label: 'Oshxona navbati bo’sh',
      note: 'Kutayotgan chek yo’q',
    },
    {
      label: 'Kassa sanog’i',
      note: 'Kassir bajaradi, terminaldan',
    },
    {
      label: 'Tasdiqlanmagan so’rovlar',
      note: '3 ta so’rov kutmoqda',
    },
    {
      label: 'Z-hisobot',
      note: 'Fiskal moduldan olinadi',
    },
  ],
  rota: [
    {
      name: 'Jasur Toshev',
      shift: '12:00 – 22:00 · kunduzgi',
      state: 'Keldi',
    },
    {
      name: 'Dilshod Nazarov',
      shift: '12:00 – 22:00 · kunduzgi',
      state: 'Keldi',
    },
    {
      name: 'Nilufar Saidova',
      shift: '16:00 – 02:00 · kechki',
      state: '18 daq kechikdi',
    },
    {
      name: 'Kamola Yusupova',
      shift: '16:00 – 02:00 · kechki',
      state: 'Keldi',
    },
    {
      name: 'Sardor Aliyev',
      shift: '12:00 – 22:00 · oshxona',
      state: 'Kelmadi',
    },
    {
      name: 'Bekzod Ismoilov',
      shift: '09:00 – 18:00 · ombor',
      state: 'Keldi',
    },
  ],
  stations: [
    {
      name: 'Grill',
      average: '14.2 daq',
      load: '34 chek · eng band',
      target: 'me’yor 12 daq',
    },
    {
      name: 'Issiq bo’lim',
      average: '11.8 daq',
      load: '48 chek',
      target: 'me’yor 12 daq',
    },
    {
      name: 'Salatlar',
      average: '5.4 daq',
      load: '26 chek',
      target: 'me’yor 7 daq',
    },
    {
      name: 'Ichimlik',
      average: '2.1 daq',
      load: '72 chek',
      target: 'me’yor 3 daq',
    },
  ],
  wasteReasons: ['Muddati o’tdi', 'Buzilgan', 'Tayyorlashda', 'Mijoz qaytardi', 'Boshqa'],
  wasteItems: ['Mol go’shti', 'Mozzarella', 'Sabzi', 'Sezar salat, tayyor', 'Non'],
  expiry: [
    {
      name: 'Mozzarella',
      batch: '#4471 · 7 kg',
      when: 'Ertaga',
    },
    {
      name: 'Qaymoq 33%',
      batch: '#4468 · 4 l',
      when: '2 kundan keyin',
    },
    {
      name: 'Tovuq filesi',
      batch: '#4472 · 19 kg',
      when: '3 kundan keyin',
    },
    {
      name: 'Sezar sousi',
      batch: '#4455 · 2 l',
      when: '5 kundan keyin',
    },
    {
      name: 'Yogurt',
      batch: '#4460 · 6 dona',
      when: '8 kundan keyin',
    },
    {
      name: 'Zaytun moyi',
      batch: '#4390 · 14 l',
      when: '62 kundan keyin',
    },
  ],
  purchase: [
    {
      name: 'Mol go’shti',
      meta: 'Qoldiq 12 kg · 1.3 kunga',
    },
    {
      name: 'Mozzarella',
      meta: 'Qoldiq 7 kg · 1.8 kunga',
    },
    {
      name: 'Tovuq filesi',
      meta: 'Qoldiq 19 kg · 2.4 kunga',
    },
    {
      name: 'Sabzi',
      meta: 'Qoldiq 26 kg · 4.1 kunga',
    },
    {
      name: 'Guruch, lazer',
      meta: 'Qoldiq 48 kg · 6.1 kunga',
    },
  ],
  swapShifts: [
    {
      day: 'Payshanba, 13-avgust',
      time: '12:00 – 22:00 · kunduzgi',
    },
    {
      day: 'Juma, 14-avgust',
      time: '16:00 – 02:00 · kechki',
    },
    {
      day: 'Shanba, 15-avgust',
      time: '12:00 – 22:00 · kunduzgi',
    },
  ],
  swapPeople: [
    {
      initials: 'DN',
      name: 'Dilshod Nazarov',
      free: 'Bo’sh · shu kuni dam olish',
    },
    {
      initials: 'KY',
      name: 'Kamola Yusupova',
      free: 'Bo’sh · kechki smenada emas',
    },
    {
      initials: 'SA',
      name: 'Sardor Aliyev',
      free: 'Band · shu kuni ishlaydi',
    },
  ],
  handback: [
    {
      label: 'Manzil topilmadi',
      note: 'Uy raqami mos kelmadi yoki kirish yopiq',
    },
    {
      label: 'Mijoz javob bermadi',
      note: 'Uch marta qo’ng’iroq qilindi, eshik ochilmadi',
    },
    {
      label: 'Mijoz rad etdi',
      note: 'Buyurtmani olishdan bosh tortdi',
    },
    {
      label: 'Texnik muammo',
      note: 'Moped buzildi yoki yo’l yopiq',
    },
  ],
  branches: [
    {
      name: 'Chilonzor',
      city: 'Toshkent',
      revenue: '6.24 mln',
      delta: '+8.1%',
      target: '92% kunlik rejadan · 6.8 mln',
      orders: '68',
      margin: '62.4%',
      staff: '14',
    },
    {
      name: 'Yunusobod',
      city: 'Toshkent',
      revenue: '4.91 mln',
      delta: '+2.4%',
      target: '91% kunlik rejadan · 5.4 mln',
      orders: '52',
      margin: '60.1%',
      staff: '11',
    },
    {
      name: 'Sergeli',
      city: 'Toshkent',
      revenue: '3.18 mln',
      delta: '−1.9%',
      target: '76% kunlik rejadan · 4.2 mln',
      orders: '39',
      margin: '57.8%',
      staff: '9',
    },
    {
      name: 'Mirzo Ulug’bek',
      city: 'Toshkent',
      revenue: '2.62 mln',
      delta: '+5.6%',
      target: '90% kunlik rejadan · 2.9 mln',
      orders: '28',
      margin: '63.9%',
      staff: '8',
    },
    {
      name: 'Termiz',
      city: 'Termiz',
      revenue: '1.47 mln',
      delta: '+11.2%',
      target: '100% kunlik rejadan · 1.4 mln',
      orders: '19',
      margin: '65.2%',
      staff: '6',
    },
  ],
  cashFlow: ['Mar', 'Apr', 'May', 'Iyn', 'Iyl', 'Avg'],
};

/** The shape every language fills. */
export type CrewMore = typeof uz;

const ru: CrewMore = {
  endShift: [
    {
      label: 'Все заказы закрыты',
      note: 'осталось {n}',
    },
    {
      label: 'Наличные сданы в кассу',
      note: '148 000 сум ожидается',
    },
    {
      label: 'Мопед сдан',
      note: 'Ключ и аккумулятор',
    },
    {
      label: 'Термосумка вымыта',
      note: 'Обязательно в конце смены',
    },
  ],
  shift: {
    sales: '1 840 000',
    salesNote: 'сум · 18 чеков · план смены 2.1 млн',
    kpis: [
      {
        label: 'Чеки',
        value: '18',
        note: '6 столов',
      },
      {
        label: 'Средний чек',
        value: '102 000',
        note: '+8.4%',
      },
      {
        label: 'Чаевые',
        value: '84 000',
        note: 'с карты',
      },
      {
        label: 'Часы',
        value: '6.4',
        note: 'с 12:00',
      },
    ],
    top: [
      {
        name: 'Плов свадебный',
        quantity: '12',
      },
      {
        name: 'Чизбургер',
        quantity: '9',
      },
      {
        name: 'Лаваш с курицей',
        quantity: '7',
      },
      {
        name: 'Зелёный чай',
        quantity: '22',
      },
    ],
  },
  bookings: [
    {
      name: 'Alisher Karimov',
      time: '19:30',
      meta: 'Стол 19 · 4 гостя · по телефону',
      note: 'День рождения · принесут торт',
    },
    {
      name: 'Malika Yo’ldosheva',
      time: '20:00',
      meta: 'Стол 12 · 2 гостя · Telegram',
      note: '',
    },
    {
      name: 'Sardor Toshmatov',
      time: '20:30',
      meta: 'Стол 14 · 6 гостей · сайт',
      note: 'Не подтверждено · нужно позвонить',
    },
    {
      name: 'Nodira Umarova',
      time: '21:00',
      meta: 'Стол 7 · 3 гостя · по телефону',
      note: '',
    },
  ],
  day: {
    earned: '96 000',
    earnedNote: 'сум · 8 доставок · 34 км',
    kpis: [
      {
        label: 'Доставки',
        value: '8',
        note: '2 в очереди',
      },
      {
        label: 'Среднее время',
        value: '24 мин',
        note: 'норма 30 мин',
      },
      {
        label: 'Расстояние',
        value: '34 km',
        note: 'мопед',
      },
      {
        label: 'Рейтинг',
        value: '4.8',
        note: '6 оценок',
      },
    ],
    log: [
      {
        address: 'Бунёдкор 12, 3-й подъезд',
        meta: '11:42 · 18 мин',
        amount: '12 000',
      },
      {
        address: 'Чиланзар 9-й квартал, дом 4',
        meta: '12:20 · 26 мин',
        amount: '12 000',
      },
      {
        address: 'Малая кольцевая 41',
        meta: '13:05 · 31 мин',
        amount: '14 000',
      },
      {
        address: 'Лутфий 28, офис 2',
        meta: '14:10 · 22 мин',
        amount: '12 000',
      },
      {
        address: 'Метро Новза, дом 5',
        meta: '15:02 · 19 мин',
        amount: '12 000',
      },
    ],
  },
  text: {
    rOwn: 'Владелец',
    rMgr: 'Менеджер',
    rWh: 'Склад',
    rWa: 'Официант',
    rCo: 'Курьер',
    tab2BadgeN: '[object Object]',
    tab3BadgeN: '[object Object]',
    revLbl: 'Выручка за сегодня · 5 филиалов',
    rev: '18 420 000',
    revDelta: '+12.4%',
    revNote: 'сум · с НДС · на 11:24',
    listLbl: 'Филиалы',
    brIntro:
      'С полосой выполнения дневного плана. Зелёный — план выполнен, синий — выше 85%, жёлтый — отстаёт.',
    brOrders: 'Заказы',
    brMargin: 'Маржа',
    brStaff: 'Смена',
    apprIntro:
      'Когда сотрудник отправляет запрос, вы получаете уведомление. Быть в ресторане не нужно.',
    apprYes: 'Согласовать',
    apprNo: 'Отклонить',
    apprEmpty: 'Нет запросов в ожидании',
    scan: 'Сканировать штрих-код',
    recvToday: 'Поставки на сегодня',
    recvAccept: 'Начать приёмку',
    countIntro:
      'Системное количество намеренно скрыто — сначала посчитайте, разницу система посчитает сама.',
    countSave: 'Сохранить пересчёт',
    countNote:
      'После сохранения изменить нельзя. При расхождении свыше 5% потребуется согласование менеджера.',
    profileLbl: 'Аккаунт',
    menuSearch: 'Поиск блюда…',
    menuNone: 'Блюдо с таким названием не найдено',
    billAdd: 'Добавить',
    billEmpty: 'Этот счёт пока пуст. Добавьте блюда кнопкой «Добавить».',
    billTotal: 'Итого',
    billSync: 'Обновить',
    dishNote: 'Комментарий повару',
    dishNotePh: 'Например: без острого',
    hrsThis: 'Текущая неделя',
    hrsNote:
      'Часы считаются по времени входа и выхода. Перерыв не вычитается автоматически — менеджер вносит вручную.',
    acctAdd: 'Добавить аккаунт',
    myOpen: 'Мои открытые столы',
    newOrder: 'Новый заказ',
    zonesNote:
      'После выбора зала показываются только его столы. Количество свободных обновляется в реальном времени.',
    searchLbl: 'Поиск',
    back: 'Назад',
    pinH: 'Начало смены',
    pinBranch: 'Филиал Чиланзар · POS-3',
    pinDemo: 'Демо PIN-коды',
    vPin: 'Вход по PIN',
    vLock: 'Экран блокировки',
    vApp: 'Приложение',
    stageNote: 'PIN определяет роль · экран блокировки зависит от роли',
    lockDate: 'Вторник, 11 августа',
    lockNote:
      'Тип уведомления зависит от роли. На запрос согласования и новый заказ можно ответить не разблокируя телефон.',
    qEmpty: 'Очередь пуста. Здесь собираются действия, выполненные офлайн.',
    qNote:
      'Действия из очереди не отправятся дважды — у каждого одноразовый ключ, который проверяет сервер.',
    ordVatNote: 'В цене уже есть НДС 12%. Сервисный сбор не берётся при самовывозе и доставке.',
    tdLines: 'Состав заказа',
    tdTotal: 'Итого',
    bdRev: 'Выручка за сегодня',
    bdHours: 'Заказы по часам',
    scanHint: 'Код считывается автоматически. Для ручного ввода удерживайте экран.',
    scanSim: 'Демо: считать следующий код',
    scanFound: 'Считанные позиции',
    scanSave: 'Завершить приёмку',
    scanNote: 'При расхождении с документом система предупредит и уведомит менеджера.',
    hbSend: 'Отправить оператору',
    hbNote: 'Заказ перейдёт другому курьеру. Причина фиксируется и не влияет на ваш рейтинг.',
    endCta: 'Закрыть смену',
    endNote:
      'После закрытия новые заказы не поступают. Заработок выплачивается с зарплатой в конце месяца.',
    swapMine: 'Мои смены',
    swapWho: 'С кем',
    swapSend: 'Отправить запрос',
    swapNote: 'Обмен вступает в силу после согласия обеих сторон и менеджера.',
    pnlNote: 'Выручка показана без НДС. Оборот кассы с НДС 18.4 млн — их не смешивают.',
    cashFlowLbl: 'Денежный поток, 6 месяцев',
    riskLbl: 'Риск по сотрудникам',
    riskNote:
      'Балл риска — не обвинение, а подсказка для проверки. Каждый случай должен смотреть человек.',
    closeDo: 'Выполнить',
    closeCta: 'Закрыть смену',
    closeNote:
      'После закрытия чеки этого дня изменить нельзя. Z-отчёт записывается в фискальный модуль.',
    rotaNote: 'Опоздания и неявки фиксируются автоматически и попадают в расчёт зарплаты.',
    stationNote:
      'Цех выше нормы показан красным. Гриль отстаёт на 2.2 минуты — не хватает одного повара.',
    wasteTotal: 'Итого потерь',
    wasteSave: 'Оформить списание',
    wasteNote:
      'После оформления автоматически снимается со склада и входит в себестоимость. Для отмены нужно согласование менеджера.',
    expiryNote: 'Товар со сроком менее двух дней — красный. Его нужно использовать первым.',
    porderTotal: 'Сумма заказа',
    porderSend: 'Отправить поставщику',
    porderSupplier: 'Поставщик',
    porderNote: 'После отправки заказ попадёт в список закупок и будет виден менеджеру.',
    shiftSales: 'Продажи за смену',
    shiftTop: 'Что я больше всего продал',
    shiftNote:
      'Чаевые выплачиваются с зарплатой в конце месяца. Наличные чаевые в систему не вносятся.',
    bookNote: 'Неподтверждённая бронь отмечена жёлтым — гостю нужно позвонить.',
    dayEarn: 'Мой заработок сегодня',
    dayLog: 'Доставки за сегодня',
    dayNote:
      'Заработок считается по фиксированной ставке за доставку и расстоянию. Чаевые отдельно.',
    openPos: 'Принять заказ',
    callsEmpty: 'Вызовов нет',
    menuIntro: 'Закончившиеся блюда показаны бледным — не предлагайте их гостю.',
    soldOut: 'Закончилось',
    coPick: 'Забрал',
    coDrop: 'Доставил',
    rtTotal: 'Осталось пути',
    rtKm: '12.8 km',
    rtTime: 'Примерное время',
    rtMins: '38 мин',
    rtNote:
      'Порядок построен по кратчайшему маршруту. При новом заказе маршрут перестраивается сам.',
    cashOnMe: 'Наличные у вас',
    cashTotal: '148 000',
    cashNote: 'сум · 2 заказа · с начала смены',
    cashRows: 'Собранные наличные',
    cashHand: 'Сдать кассиру',
    cashHandNote:
      'После сдачи кассир пересчитывает и подтверждает. До подтверждения сумма остаётся за вами.',
    moreNote:
      'Это приложение не заменяет систему на компьютере. Оно делает только то, что нужно, когда вас нет в ресторане.',
  },
  pnl: [
    {
      label: 'Выручка без НДС',
      value: '16 446 000',
    },
    {
      label: 'Себестоимость',
      value: '−6 184 000',
    },
    {
      label: 'Валовая прибыль',
      value: '10 262 000',
    },
    {
      label: 'Оплата труда',
      value: '−3 620 000',
    },
    {
      label: 'Аренда и коммунальные',
      value: '−1 480 000',
    },
    {
      label: 'Прочие расходы',
      value: '−1 080 000',
    },
    {
      label: 'Чистая прибыль',
      value: '4 082 000',
    },
  ],
  people: [
    {
      initials: 'JT',
      name: 'Jasur Toshev',
      role: 'Официант · Чиланзар',
      sales: '1.84 mln',
      meta: '18 чек',
    },
    {
      initials: 'DN',
      name: 'Dilshod Nazarov',
      role: 'Официант · Чиланзар',
      sales: '1.52 mln',
      meta: '16 чек',
    },
    {
      initials: 'NS',
      name: 'Nilufar Saidova',
      role: 'Кассир · Чиланзар',
      sales: '1.31 mln',
      meta: '14 чек',
    },
    {
      initials: 'KY',
      name: 'Kamola Yusupova',
      role: 'Официант · Юнусабад',
      sales: '1.08 mln',
      meta: '12 чек',
    },
    {
      initials: 'AR',
      name: 'Aziza Rahimova',
      role: 'Менеджер · Чиланзар',
      sales: '—',
      meta: 'на смене',
    },
    {
      initials: 'BI',
      name: 'Bekzod Ismoilov',
      role: 'Кладовщик · Чиланзар',
      sales: '—',
      meta: 'на смене',
    },
  ],
  risk: [
    {
      name: 'Jasur Toshev',
      score: '78',
      meta: '6 отмен · 4 удаления · скидки 340 000',
    },
    {
      name: 'Nilufar Saidova',
      score: '52',
      meta: '2 возврата · расхождение кассы 32 000',
    },
    {
      name: 'Dilshod Nazarov',
      score: '24',
      meta: '1 отмена · скидок нет',
    },
    {
      name: 'Kamola Yusupova',
      score: '11',
      meta: 'Никаких признаков',
    },
  ],
  closing: [
    {
      label: 'Все столы закрыты',
      note: '32 из 32 столов',
    },
    {
      label: 'Очередь кухни пуста',
      note: 'Нет ожидающих чеков',
    },
    {
      label: 'Пересчёт кассы',
      note: 'Выполняет кассир на терминале',
    },
    {
      label: 'Несогласованные запросы',
      note: '3 запросов в ожидании',
    },
    {
      label: 'Z-отчёт',
      note: 'Снимается с фискального модуля',
    },
  ],
  rota: [
    {
      name: 'Jasur Toshev',
      shift: '12:00 – 22:00 · день',
      state: 'На месте',
    },
    {
      name: 'Dilshod Nazarov',
      shift: '12:00 – 22:00 · день',
      state: 'На месте',
    },
    {
      name: 'Nilufar Saidova',
      shift: '16:00 – 02:00 · вечер',
      state: 'Опоздал 18 мин',
    },
    {
      name: 'Kamola Yusupova',
      shift: '16:00 – 02:00 · вечер',
      state: 'На месте',
    },
    {
      name: 'Sardor Aliyev',
      shift: '12:00 – 22:00 · кухня',
      state: 'Не пришёл',
    },
    {
      name: 'Bekzod Ismoilov',
      shift: '09:00 – 18:00 · склад',
      state: 'На месте',
    },
  ],
  stations: [
    {
      name: 'Гриль',
      average: '14.2 мин',
      load: '34 чека · самый загруженный',
      target: 'норма 12 мин',
    },
    {
      name: 'Горячий цех',
      average: '11.8 мин',
      load: '48 чеков',
      target: 'норма 12 мин',
    },
    {
      name: 'Салаты',
      average: '5.4 мин',
      load: '26 чеков',
      target: 'норма 7 мин',
    },
    {
      name: 'Напитки',
      average: '2.1 мин',
      load: '72 чека',
      target: 'норма 3 мин',
    },
  ],
  wasteReasons: ['Истёк срок', 'Испорчено', 'При готовке', 'Возврат гостя', 'Другое'],
  wasteItems: ['Говядина', 'Моцарелла', 'Морковь', 'Салат Цезарь готовый', 'Лепёшка'],
  expiry: [
    {
      name: 'Моцарелла',
      batch: '#4471 · 7 kg',
      when: 'Завтра',
    },
    {
      name: 'Сливки 33%',
      batch: '#4468 · 4 l',
      when: '2 дн',
    },
    {
      name: 'Куриное филе',
      batch: '#4472 · 19 kg',
      when: '3 дн',
    },
    {
      name: 'Соус Цезарь',
      batch: '#4455 · 2 l',
      when: '5 дн',
    },
    {
      name: 'Йогурт',
      batch: '#4460 · 6 шт',
      when: '8 дн',
    },
    {
      name: 'Оливковое масло',
      batch: '#4390 · 14 l',
      when: '62 дн',
    },
  ],
  purchase: [
    {
      name: 'Говядина',
      meta: 'Остаток 12 кг · на 1.3 дня',
    },
    {
      name: 'Моцарелла',
      meta: 'Остаток 7 кг · на 1.8 дня',
    },
    {
      name: 'Куриное филе',
      meta: 'Остаток 19 кг · на 2.4 дня',
    },
    {
      name: 'Морковь',
      meta: 'Остаток 26 кг · на 4.1 дня',
    },
    {
      name: 'Рис лазер',
      meta: 'Остаток 48 кг · на 6.1 дня',
    },
  ],
  swapShifts: [
    {
      day: 'Четверг, 13 августа',
      time: '12:00 – 22:00 · день',
    },
    {
      day: 'Пятница, 14 августа',
      time: '16:00 – 02:00 · вечер',
    },
    {
      day: 'Суббота, 15 августа',
      time: '12:00 – 22:00 · день',
    },
  ],
  swapPeople: [
    {
      initials: 'DN',
      name: 'Dilshod Nazarov',
      free: 'Свободен · в этот день выходной',
    },
    {
      initials: 'KY',
      name: 'Kamola Yusupova',
      free: 'Свободна · не в вечерней смене',
    },
    {
      initials: 'SA',
      name: 'Sardor Aliyev',
      free: 'Занят · работает в этот день',
    },
  ],
  handback: [
    {
      label: 'Адрес не найден',
      note: 'Номер дома не совпал или вход закрыт',
    },
    {
      label: 'Клиент не отвечает',
      note: 'Позвонил трижды, дверь не открыли',
    },
    {
      label: 'Клиент отказался',
      note: 'Отказался принимать заказ',
    },
    {
      label: 'Техническая проблема',
      note: 'Мопед сломался или дорога закрыта',
    },
  ],
  branches: [
    {
      name: 'Chilonzor',
      city: 'Toshkent',
      revenue: '6.24 млн',
      delta: '+8.1%',
      target: '92% от плана на день · 6.8 млн',
      orders: '68',
      margin: '62.4%',
      staff: '14',
    },
    {
      name: 'Yunusobod',
      city: 'Toshkent',
      revenue: '4.91 млн',
      delta: '+2.4%',
      target: '91% от плана на день · 5.4 млн',
      orders: '52',
      margin: '60.1%',
      staff: '11',
    },
    {
      name: 'Sergeli',
      city: 'Toshkent',
      revenue: '3.18 млн',
      delta: '−1.9%',
      target: '76% от плана на день · 4.2 млн',
      orders: '39',
      margin: '57.8%',
      staff: '9',
    },
    {
      name: 'Mirzo Ulug’bek',
      city: 'Toshkent',
      revenue: '2.62 млн',
      delta: '+5.6%',
      target: '90% от плана на день · 2.9 млн',
      orders: '28',
      margin: '63.9%',
      staff: '8',
    },
    {
      name: 'Termiz',
      city: 'Termiz',
      revenue: '1.47 млн',
      delta: '+11.2%',
      target: '100% от плана на день · 1.4 млн',
      orders: '19',
      margin: '65.2%',
      staff: '6',
    },
  ],
  cashFlow: ['Мар', 'Апр', 'Май', 'Июн', 'Июл', 'Авг'],
};

const en: CrewMore = {
  endShift: [
    {
      label: 'All orders closed',
      note: '{n} left',
    },
    {
      label: 'Cash handed to the till',
      note: '148 000 so’m outstanding',
    },
    {
      label: 'Moped returned',
      note: 'Key and battery',
    },
    {
      label: 'Thermal bag cleaned',
      note: 'Required at the end of every shift',
    },
  ],
  shift: {
    sales: '1 840 000',
    salesNote: 'so’m · 18 tickets · shift target 2.1M',
    kpis: [
      {
        label: 'Tickets',
        value: '18',
        note: '6 tables',
      },
      {
        label: 'Average ticket',
        value: '102 000',
        note: '+8.4%',
      },
      {
        label: 'Tips',
        value: '84 000',
        note: 'from cards',
      },
      {
        label: 'Hours',
        value: '6.4',
        note: 'since 12:00',
      },
    ],
    top: [
      {
        name: 'Plov, wedding style',
        quantity: '12',
      },
      {
        name: 'Cheeseburger',
        quantity: '9',
      },
      {
        name: 'Chicken lavash',
        quantity: '7',
      },
      {
        name: 'Green tea',
        quantity: '22',
      },
    ],
  },
  bookings: [
    {
      name: 'Alisher Karimov',
      time: '19:30',
      meta: 'Table 19 · 4 guests · by phone',
      note: 'Birthday · they are bringing a cake',
    },
    {
      name: 'Malika Yo’ldosheva',
      time: '20:00',
      meta: 'Table 12 · 2 guests · Telegram',
      note: '',
    },
    {
      name: 'Sardor Toshmatov',
      time: '20:30',
      meta: 'Table 14 · 6 guests · website',
      note: 'Unconfirmed · needs a call',
    },
    {
      name: 'Nodira Umarova',
      time: '21:00',
      meta: 'Table 7 · 3 guests · by phone',
      note: '',
    },
  ],
  day: {
    earned: '96 000',
    earnedNote: 'so’m · 8 deliveries · 34 km',
    kpis: [
      {
        label: 'Deliveries',
        value: '8',
        note: '2 in the queue',
      },
      {
        label: 'Average time',
        value: '24 min',
        note: 'target 30 min',
      },
      {
        label: 'Distance',
        value: '34 km',
        note: 'moped',
      },
      {
        label: 'Rating',
        value: '4.8',
        note: '6 ratings',
      },
    ],
    log: [
      {
        address: 'Bunyodkor 12, entrance 3',
        meta: '11:42 · 18 min',
        amount: '12 000',
      },
      {
        address: 'Chilonzor block 9, house 4',
        meta: '12:20 · 26 min',
        amount: '12 000',
      },
      {
        address: 'Katta Xalqa 41',
        meta: '13:05 · 31 min',
        amount: '14 000',
      },
      {
        address: 'Lutfiy 28, office 2',
        meta: '14:10 · 22 min',
        amount: '12 000',
      },
      {
        address: 'Novza metro, house 5',
        meta: '15:02 · 19 min',
        amount: '12 000',
      },
    ],
  },
  text: {
    rOwn: 'Owner',
    rMgr: 'Manager',
    rWh: 'Store',
    rWa: 'Waiter',
    rCo: 'Courier',
    tab2BadgeN: '[object Object]',
    tab3BadgeN: '[object Object]',
    revLbl: 'Revenue today · 5 branches',
    rev: '18 420 000',
    revDelta: '+12.4%',
    revNote: 'so’m · incl. VAT · as of 11:24',
    listLbl: 'Branches',
    brIntro:
      'With a bar showing attainment against the daily target. Green — target met, blue — above 85%, amber — behind.',
    brOrders: 'Orders',
    brMargin: 'Margin',
    brStaff: 'On shift',
    apprIntro:
      'When an employee sends a request you get a notification. You do not need to be in the restaurant.',
    apprYes: 'Approve',
    apprNo: 'Decline',
    apprEmpty: 'Nothing waiting for you',
    scan: 'Scan a barcode',
    recvToday: 'Deliveries today',
    recvAccept: 'Start receiving',
    countIntro:
      'The system quantity is deliberately hidden — count first, and the system works out the variance.',
    countSave: 'Save the count',
    countNote: 'Once saved it cannot be changed. A variance above 5% needs manager approval.',
    profileLbl: 'Account',
    menuSearch: 'Search a dish…',
    menuNone: 'No dish matches that name',
    billAdd: 'Add',
    billEmpty: 'This bill is empty. Use “Add” to put dishes on it.',
    billTotal: 'Total',
    billSync: 'Refresh',
    dishNote: 'Note for the kitchen',
    dishNotePh: 'For example: not spicy',
    hrsThis: 'This week',
    hrsNote:
      'Hours come from sign-in and sign-out. Breaks are not deducted automatically — the manager enters them.',
    acctAdd: 'Add an account',
    myOpen: 'My open tables',
    newOrder: 'New order',
    zonesNote: 'Picking a zone filters the tables to that zone. The free count updates live.',
    searchLbl: 'Search',
    back: 'Back',
    pinH: 'Start of shift',
    pinBranch: 'Chilonzor branch · POS-3',
    pinDemo: 'Demo PINs',
    vPin: 'PIN entry',
    vLock: 'Lock screen',
    vApp: 'App',
    stageNote: 'The PIN picks the role · the lock screen changes with it',
    lockDate: 'Tuesday, 11 August',
    lockNote:
      'The notification type follows the role. Approval requests and new orders can be answered without unlocking.',
    qEmpty: 'The queue is empty. Actions taken offline collect here.',
    qNote: 'Queued actions never send twice — each carries a one-time key the server checks.',
    ordVatNote: 'VAT 12% is already in the price. No service charge on takeaway or delivery.',
    tdLines: 'Order lines',
    tdTotal: 'Total',
    bdRev: 'Revenue today',
    bdHours: 'Orders by hour',
    scanHint: 'The code reads automatically. Hold the screen to type it in.',
    scanSim: 'Demo: read the next code',
    scanFound: 'Scanned lines',
    scanSave: 'Finish receiving',
    scanNote:
      'If the count differs from the document, the system warns you and notifies the manager.',
    hbSend: 'Send to the operator',
    hbNote:
      'The order goes to another courier. The reason is logged and does not affect your rating.',
    endCta: 'End the shift',
    endNote:
      'No new orders arrive once the shift is closed. Earnings are paid with salary at month end.',
    swapMine: 'My shifts',
    swapWho: 'With whom',
    swapSend: 'Send the request',
    swapNote: 'A swap takes effect once both people and the manager agree.',
    pnlNote: 'Revenue is shown ex-VAT. Till turnover incl. VAT is 18.4M — the two are never mixed.',
    cashFlowLbl: 'Cash flow, last 6 months',
    riskLbl: 'Risk by employee',
    riskNote:
      'A risk score is not an accusation — it is a prompt to look. Every case needs a human review.',
    closeDo: 'Do it',
    closeCta: 'Close the shift',
    closeNote:
      'Once closed, this day’s tickets cannot be changed. The Z report is written to the fiscal module.',
    rotaNote: 'Lateness and no-shows are recorded automatically and feed into payroll.',
    stationNote:
      'A station over target shows red. Grill is 2.2 minutes behind today — one cook short.',
    wasteTotal: 'Total loss',
    wasteSave: 'Record the waste',
    wasteNote:
      'Once recorded it is deducted from stock and enters food cost. Reversing it needs manager approval.',
    expiryNote: 'Anything under two days shows red. Use it first.',
    porderTotal: 'Order total',
    porderSend: 'Send to the supplier',
    porderSupplier: 'Supplier',
    porderNote: 'Once sent, the order appears in the purchase list and the manager sees it.',
    shiftSales: 'Shift sales',
    shiftTop: 'My top sellers',
    shiftNote: 'Tips are paid with salary at month end. Cash tips are not entered into the system.',
    bookNote: 'An unconfirmed booking is marked amber — the guest needs a call.',
    dayEarn: 'My earnings today',
    dayLog: 'Today’s deliveries',
    dayNote: 'Earnings are a fixed fee per delivery plus distance. Tips are separate.',
    openPos: 'Take an order',
    callsEmpty: 'No calls',
    menuIntro: 'Sold-out dishes are dimmed — do not offer them to the guest.',
    soldOut: 'Sold out',
    coPick: 'Picked up',
    coDrop: 'Delivered',
    rtTotal: 'Distance left',
    rtKm: '12.8 km',
    rtTime: 'Estimated time',
    rtMins: '38 min',
    rtNote:
      'The order is built along the shortest route. When a new order arrives the route rebuilds itself.',
    cashOnMe: 'Cash on you',
    cashTotal: '148 000',
    cashNote: 'so’m · 2 orders · since the shift began',
    cashRows: 'Cash collected',
    cashHand: 'Hand in to the cashier',
    cashHandNote:
      'Once handed in the cashier counts and confirms it. Until then the amount stays against your name.',
    moreNote:
      'This app does not replace the desktop system. It does only what you need when you are not in the restaurant.',
  },
  pnl: [
    {
      label: 'Revenue, ex-VAT',
      value: '16 446 000',
    },
    {
      label: 'Cost of goods',
      value: '−6 184 000',
    },
    {
      label: 'Gross profit',
      value: '10 262 000',
    },
    {
      label: 'Labour',
      value: '−3 620 000',
    },
    {
      label: 'Rent and utilities',
      value: '−1 480 000',
    },
    {
      label: 'Other expenses',
      value: '−1 080 000',
    },
    {
      label: 'Net profit',
      value: '4 082 000',
    },
  ],
  people: [
    {
      initials: 'JT',
      name: 'Jasur Toshev',
      role: 'Waiter · Chilonzor',
      sales: '1.84 mln',
      meta: '18 tickets',
    },
    {
      initials: 'DN',
      name: 'Dilshod Nazarov',
      role: 'Waiter · Chilonzor',
      sales: '1.52 mln',
      meta: '16 tickets',
    },
    {
      initials: 'NS',
      name: 'Nilufar Saidova',
      role: 'Cashier · Chilonzor',
      sales: '1.31 mln',
      meta: '14 tickets',
    },
    {
      initials: 'KY',
      name: 'Kamola Yusupova',
      role: 'Waiter · Yunusobod',
      sales: '1.08 mln',
      meta: '12 tickets',
    },
    {
      initials: 'AR',
      name: 'Aziza Rahimova',
      role: 'Manager · Chilonzor',
      sales: '—',
      meta: 'on shift',
    },
    {
      initials: 'BI',
      name: 'Bekzod Ismoilov',
      role: 'Store · Chilonzor',
      sales: '—',
      meta: 'on shift',
    },
  ],
  risk: [
    {
      name: 'Jasur Toshev',
      score: '78',
      meta: '6 voids · 4 deletions · 340 000 in discounts',
    },
    {
      name: 'Nilufar Saidova',
      score: '52',
      meta: '2 refunds · 32 000 cash variance',
    },
    {
      name: 'Dilshod Nazarov',
      score: '24',
      meta: '1 void · no discounts',
    },
    {
      name: 'Kamola Yusupova',
      score: '11',
      meta: 'Nothing flagged',
    },
  ],
  closing: [
    {
      label: 'All tables closed',
      note: '32 of 32 tables',
    },
    {
      label: 'Kitchen queue empty',
      note: 'No tickets waiting',
    },
    {
      label: 'Cash count',
      note: 'The cashier does this at the till',
    },
    {
      label: 'Pending approvals',
      note: '3 waiting',
    },
    {
      label: 'Z report',
      note: 'Taken from the fiscal module',
    },
  ],
  rota: [
    {
      name: 'Jasur Toshev',
      shift: '12:00 – 22:00 · day',
      state: 'Clocked in',
    },
    {
      name: 'Dilshod Nazarov',
      shift: '12:00 – 22:00 · day',
      state: 'Clocked in',
    },
    {
      name: 'Nilufar Saidova',
      shift: '16:00 – 02:00 · evening',
      state: '18 min late',
    },
    {
      name: 'Kamola Yusupova',
      shift: '16:00 – 02:00 · evening',
      state: 'Clocked in',
    },
    {
      name: 'Sardor Aliyev',
      shift: '12:00 – 22:00 · kitchen',
      state: 'No show',
    },
    {
      name: 'Bekzod Ismoilov',
      shift: '09:00 – 18:00 · store',
      state: 'Clocked in',
    },
  ],
  stations: [
    {
      name: 'Grill',
      average: '14.2 min',
      load: '34 tickets · busiest',
      target: 'target 12 min',
    },
    {
      name: 'Hot line',
      average: '11.8 min',
      load: '48 tickets',
      target: 'target 12 min',
    },
    {
      name: 'Salads',
      average: '5.4 min',
      load: '26 tickets',
      target: 'target 7 min',
    },
    {
      name: 'Drinks',
      average: '2.1 min',
      load: '72 tickets',
      target: 'target 3 min',
    },
  ],
  wasteReasons: ['Expired', 'Spoiled', 'Prep loss', 'Guest returned', 'Other'],
  wasteItems: ['Beef', 'Mozzarella', 'Carrot', 'Caesar salad, made', 'Flatbread'],
  expiry: [
    {
      name: 'Mozzarella',
      batch: '#4471 · 7 kg',
      when: 'Tomorrow',
    },
    {
      name: 'Cream 33%',
      batch: '#4468 · 4 l',
      when: '2 days',
    },
    {
      name: 'Chicken fillet',
      batch: '#4472 · 19 kg',
      when: '3 days',
    },
    {
      name: 'Caesar dressing',
      batch: '#4455 · 2 l',
      when: '5 days',
    },
    {
      name: 'Yoghurt',
      batch: '#4460 · 6 pcs',
      when: '8 days',
    },
    {
      name: 'Olive oil',
      batch: '#4390 · 14 l',
      when: '62 days',
    },
  ],
  purchase: [
    {
      name: 'Beef',
      meta: '12 kg left · 1.3 days',
    },
    {
      name: 'Mozzarella',
      meta: '7 kg left · 1.8 days',
    },
    {
      name: 'Chicken fillet',
      meta: '19 kg left · 2.4 days',
    },
    {
      name: 'Carrot',
      meta: '26 kg left · 4.1 days',
    },
    {
      name: 'Rice, lazer',
      meta: '48 kg left · 6.1 days',
    },
  ],
  swapShifts: [
    {
      day: 'Thursday, 13 August',
      time: '12:00 – 22:00 · day',
    },
    {
      day: 'Friday, 14 August',
      time: '16:00 – 02:00 · evening',
    },
    {
      day: 'Saturday, 15 August',
      time: '12:00 – 22:00 · day',
    },
  ],
  swapPeople: [
    {
      initials: 'DN',
      name: 'Dilshod Nazarov',
      free: 'Free · off that day',
    },
    {
      initials: 'KY',
      name: 'Kamola Yusupova',
      free: 'Free · not on the evening shift',
    },
    {
      initials: 'SA',
      name: 'Sardor Aliyev',
      free: 'Busy · working that day',
    },
  ],
  handback: [
    {
      label: 'Address not found',
      note: 'The house number did not match or the entrance is closed',
    },
    {
      label: 'Guest unreachable',
      note: 'Called three times, nobody answered the door',
    },
    {
      label: 'Guest refused',
      note: 'Refused to take the order',
    },
    {
      label: 'Vehicle problem',
      note: 'The moped broke down or the road is closed',
    },
  ],
  branches: [
    {
      name: 'Chilonzor',
      city: 'Toshkent',
      revenue: '6.24 M',
      delta: '+8.1%',
      target: '92% of the daily target · 6.8 M',
      orders: '68',
      margin: '62.4%',
      staff: '14',
    },
    {
      name: 'Yunusobod',
      city: 'Toshkent',
      revenue: '4.91 M',
      delta: '+2.4%',
      target: '91% of the daily target · 5.4 M',
      orders: '52',
      margin: '60.1%',
      staff: '11',
    },
    {
      name: 'Sergeli',
      city: 'Toshkent',
      revenue: '3.18 M',
      delta: '−1.9%',
      target: '76% of the daily target · 4.2 M',
      orders: '39',
      margin: '57.8%',
      staff: '9',
    },
    {
      name: 'Mirzo Ulug’bek',
      city: 'Toshkent',
      revenue: '2.62 M',
      delta: '+5.6%',
      target: '90% of the daily target · 2.9 M',
      orders: '28',
      margin: '63.9%',
      staff: '8',
    },
    {
      name: 'Termiz',
      city: 'Termiz',
      revenue: '1.47 M',
      delta: '+11.2%',
      target: '100% of the daily target · 1.4 M',
      orders: '19',
      margin: '65.2%',
      staff: '6',
    },
  ],
  cashFlow: ['Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'],
};

const MORE_COPY = { uz, ru, en } as const;

/** The sub-screen copy for one reader. */
export function moreCopy(lang: 'uz' | 'ru' | 'en'): CrewMore {
  return MORE_COPY[lang] ?? uz;
}
