apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: restaurant-campus-web
  namespace: restaurant-campus
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: restaurant-campus-web
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: restaurant-campus-api
  namespace: restaurant-campus
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: restaurant-campus-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: restaurant-campus-api-worker
  namespace: restaurant-campus
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: restaurant-campus-api-worker
