/**
 * Everything the two guest surfaces say, in the three languages.
 *
 * This file is a **temporary home**. Copy belongs in `src/i18n`, which another
 * session owns; the same block has been sent there and this module is what the
 * screens read until it lands. When it does, the only change is the body of
 * `guestCopy` below — every component reads through `useGuestCopy()` and none
 * of them names a key twice.
 *
 * The prose is the designer's own, lifted from
 * `Smart Restaurant Mehmon.dc.html` and `Osh Xona - Restoran sayti.dc.html`.
 * Nothing here was machine-translated: Uzbek is the authoring language,
 * Russian is neutral-professional, English is the most concise, and the three
 * are not word-for-word because the handoff says they must not be.
 *
 * What is deliberately **not** here: anything that reads the same in all three
 * languages. `Click`, `Payme`, `Uzcard`, `VEG`, `OSH10`, branch names, phone
 * numbers, `4.9`, `06:00`, `+35%` — those are data, and a catalogue holding
 * them is three files waiting for two of them to fall behind. They live in the
 * `*-data.ts` beside each screen.
 *
 * `{name}`-style holes are filled by `fill()` rather than by next-intl's ICU,
 * because this module has to work before it is a catalogue. The call sites do
 * not change when it becomes one.
 */

/** A hole in a sentence, filled by name so the three languages can reorder. */
export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (whole, key: string) =>
    key in values ? String(values[key]) : whole,
  );
}

const uz = {
  qr: {
    scan: {
      branch: '{name} filiali',
      table: 'Sizning stolingiz · {table}',
      tableMeta: 'Ofitsiant {waiter} · {guests} mehmon',
      openMenu: "Menyuni ko'rish",
      openMenuSub: '{count} taom · narxlar QQS bilan',
      callWaiter: 'Ofitsiantni chaqirish',
      callWaiterSub: "O'rtacha javob 40 soniya",
      payBill: "Hisobni to'lash",
      payBillSub: 'Karta, Click yoki Payme',
      noApp:
        "Ilova yuklash shart emas. Ro'yxatdan o'tish ham talab qilinmaydi — buyurtma stol raqamiga bog'lanadi.",
      wifi: 'Wi-Fi: {network} · parolsiz',
    },
    menu: {
      title: 'Menyu',
      count: '{count} taom',
      countFor: '{count} taom · “{query}”',
      search: 'Qidirish',
      searchPlaceholder: 'Taom qidirish',
      clear: 'Qidiruvni tozalash',
      all: 'Hammasi',
      veg: 'VEG',
      hot: 'ACHCHIQ',
      soldOut: 'TUGADI',
      soldOutNote: 'Bugun tugadi. Ertaga qaytadi.',
      empty: 'Taom topilmadi',
      emptySub: 'Boshqa nom kiriting yoki kategoriyadan tanlang.',
      showAll: "Hammasini ko'rsatish",
      viewOrder: "Buyurtmani ko'rish",
      added: '{name} · savatga qo’shildi',
      addedMany: '{count} × {name} · savatga qo’shildi',
    },
    dish: {
      back: 'Menyuga qaytish',
      ingredients: 'Tarkibi',
      allergens: 'Allergenlar',
      addons: "Qo'shimchalar",
      optional: 'ixtiyoriy',
      note: 'Oshxonaga izoh',
      notePlaceholder: 'Masalan: piyoz solmang',
      add: "Qo'shish ·",
      decrease: 'Kamaytirish',
      increase: "Ko'paytirish",
      noAllergens: 'Allergen yo’q.',
      addonList: {
        meat: "Qo'shimcha go'sht",
        qazi: 'Qazi',
        egg: 'Bedana tuxumi',
        noFat: "Dumba yog'i solmang",
      },
    },
    status: {
      title: 'Buyurtma holati',
      order: 'Buyurtma № {number}',
      lines: '{count} pozitsiya',
      cooking: 'Tayyorlanmoqda',
      about: 'Taxminan',
      minutes: 'daqiqa',
      readyBy: "Tayyor bo'ladi: {time}",
      yourOrder: 'Buyurtmangiz',
      basket: 'Savat',
      empty: "Savat bo'sh. Menyudan taom qo'shsangiz, shu yerda ko'rinadi.",
      addMore: "Yana buyurtma qo'shish",
      pending: 'kutilmoqda',
      // The send button on the basket — `POST /public/tables/{token}/order`.
      // Three words rather than one, because the middle state is what stops
      // a second tap: a button that still says "send" while it is sending
      // is a button somebody presses again, and two taps are two orders.
      send: 'Oshxonaga yuborish',
      sending: 'Yuborilmoqda…',
      sent: 'Oshxonaga yuborildi',
      steps: {
        sent: 'Buyurtma yuborildi',
        accepted: 'Oshxona qabul qildi',
        cooking: 'Tayyorlanmoqda',
        ready: 'Tayyor',
        served: 'Stolga berildi',
      },
    },
    bill: {
      title: 'Hisob',
      table: 'Stol {table} · {guests} mehmon',
      items: 'Taomlar',
      service: 'Xizmat haqi {percent}%',
      discount: 'Chegirma · Oltin karta {percent}%',
      total: 'Jami',
      vat: 'shundan QQS {percent}%',
      split: 'Hisobni bo’lish',
      splitSub: 'Teng bo’linadi. Yaxlitlash farqi birinchi chekka qo’shiladi.',
      splitWays: 'mehmon',
      splitEach: 'Har biriga',
      splitFirst: 'Birinchi chekka',
      railApp: 'Ilova ochiladi',
      railWaiter: 'Ofitsiant chaqiriladi',
      splitNote: "Har bir mehmon o'z ulushini alohida to'laydi. Ofitsiant chaqirilmaydi.",
      close: 'Yopish',
      howPay: "Qanday to'laysiz",
      tip: 'Choypuli',
      tipNote: "to'liq ofitsiantga",
      tipNone: "Yo'q",
      noTip: 'Choypuli qo’shilmadi',
      /*
       * "To'lash" promised a payment. `PAYMENTS_SANDBOX_ENABLED` means no money
       * moves: the button posts a waiter-call-and-close request, which is real
       * and useful, and then the guest was taken to a "paid" screen having paid
       * nothing. The label now names the act — the waiter is what closes the
       * bill — and it goes back to "Pay" the day Payme and Click keys land.
       */
      pay: 'Ofitsiantni chaqirish · hisob',
      cashRounded: 'naqd to’lovda {amount} ga yaxlitlanadi',
    },
    rating: {
      paid: "To'lov qabul qilindi",
      paidLine: '{amount} {currency} · {method} · chek soliq.uz da',
      /*
       * The button used to say "download the receipt" and the toast said the
       * PDF had arrived. Nothing was generated, mailed or downloaded —
       * `FISCAL_DRIVER=none` and there is no guest-scoped receipt endpoint — so
       * a guest who needed the document for expenses had nothing and did not
       * know it. The words say what actually happens: the till prints it.
       */
      receipt: 'Chek kerakmi?',
      receiptDone: 'Chekni kassadan so‘rang — hozircha faqat qog‘ozda',
      title: "Bugun qanday o'tdi?",
      sub: 'Baho ofitsiantga va menejerga ko’rinadi',
      whatGood: "Nima yaxshi bo'ldi?",
      commentPlaceholder: 'Xohlasangiz, batafsil yozing',
      loyalty: 'Keyingi tashrifda {percent}% chegirma olish uchun telefon raqamimni saqlang',
      send: 'Bahoni yuborish',
      skip: 'Keyinroq',
      skipped: 'Baho o’tkazib yuborildi',
      thanks: 'Rahmat · {stars}★ · menejerga yuborildi',
      stars: ['Yaxshi emas edi', "O'rtacha", 'Yaxshi', 'Juda yaxshi', 'Ajoyib'],
      tags: [
        'Taom mazali',
        'Tez keldi',
        "Ofitsiant e'tiborli",
        'Toza',
        'Narx munosib',
        'Jim va tinch',
      ],
    },
    scanner: {
      title: 'Stoldagi QR kod',
      body: "Kodni ramka ichiga oling — menyu o'zi ochiladi.",
      allowTitle: 'Kamera hali yoqilmagan',
      allowBody:
        "Kodni o'qish uchun kamera kerak. Rasm saqlanmaydi va hech qayerga yuborilmaydi — ilova faqat kod ichidagi manzilni o'qiydi.",
      allow: 'Kamerani yoqish',
      deniedTitle: 'Kameraga ruxsat yopiq',
      deniedBody:
        "Ruxsat telefon sozlamalarida o'chirilgan, shuning uchun ilova uni qayta so'ray olmaydi. Sozlamalardan yoqing yoki stol raqamini ofitsiantdan so'rang.",
      settings: 'Sozlamalarni ochish',
      wrongTitle: 'Bu stol kodi emas',
      wrongBody: "O'qilgan kod boshqa manzilga olib boradi. Stol ustidagi kodni qayta o'qing.",
      again: 'Qayta o’qish',
    },
    common: {
      waiterCalled: 'Ofitsiant chaqirildi',
      waiterOnWay: '{waiter} yo’lda',
      demoPayment: 'Namoyish rejimi · to’lov yuborilmadi',
      loyaltyOn: 'Oltin karta chegirmasi qo’llandi · {percent}%',
      loyaltyOff: 'Chegirma olib tashlandi',
      offline: 'Menyu namunaviy — server javob bermadi',
      menuUnwritten: 'Menyu hali kiritilmagan — tez orada.',
      retry: 'Qayta urinish',
    },
  },

  site: {
    nav: {
      home: 'Bosh sahifa',
      menu: 'Menyu',
      book: 'Stol bandlash',
      track: 'Buyurtmani kuzatish',
      about: 'Biz haqimizda',
      cart: 'Savat',
      theme: 'Kunduzgi va tungi rejim',
      tagline: 'Toshkent · {count} filial',
    },
    home: {
      openNow: 'Hozir ochiq · {until} gacha',
      closedNow: 'Hozir yopiq',
      title: 'Osh ustida gaplashadigan joy',
      body: "Qazili Toshkent oshi, cho'g'da pishirilgan kabob va kuniga uch marta yopiladigan tandir non. Yetkazamiz yoki kutib olamiz.",
      ratings: '· {count} baho',
      eta: 'Yetkazish {range} daqiqa',
      freeFrom: '{amount} so’mdan bepul',
      ctaOrder: 'Menyuni ochish',
      ctaBook: 'Stol bandlash',
      popular: "Ko'p buyurtma qilinadi",
      popularSub: 'Oxirgi 30 kun ichida',
      seeAll: 'Butun menyu',
      branches: 'Filiallar',
      branchesSub: 'Olib ketish va bandlash uchun eng yaqinini tanlang',
      open: 'Ochiq',
      closed: 'Yopiq',
      mostOrdered: "Eng ko'p buyurtma",
      quick: {
        delivery: 'Yetkazish',
        deliverySub: '{range} daqiqa, {amount} so’mdan bepul',
        pickup: 'Olib ketish',
        pickupSub: "{minutes} daqiqada tayyor, xizmat haqi yo'q",
        book: 'Stol bandlash',
        bookSub: 'Zal, ayvon yoki xona — bepul',
        large: 'Katta buyurtma',
        largeSub: "To'y va yig'in uchun · {people} kishidan",
        largeToast: 'Katta buyurtma uchun {phone} ga qo’ng’iroq qiling',
      },
      promises: [
        {
          value: '12',
          head: 'yil bir joyda',
          body: '2014 yildan Chilonzorda. O’sha oshpaz, o’sha qozon.',
        },
        {
          value: '06:00',
          head: 'da bozorga chiqamiz',
          body: 'Go’sht va sabzavot har kuni yangi olinadi, muzlatilgan mahsulot ishlatilmaydi.',
        },
        {
          value: '4.9',
          head: 'o’rtacha baho',
          body: '1 240 mijoz bahosidan. Har bir izoh o’qiladi va javob beriladi.',
        },
      ],
      popularAny: 'Menyudan tanlab olingan',
      baked: 'Kuniga uch marta',
      orders: '· {count} marta buyurtma',
    },
    menu: {
      title: 'Menyu',
      sub: '{count} pozitsiya · narxlar QQS bilan · kuniga yangilanadi',
      found: '{count} ta taom topildi',
      search: 'Taom nomi bo’yicha qidirish',
      add: "Qo'shish",
      soldOut: 'Bugun tugadi',
      soldOutToast: 'Bu taom bugun tugagan',
      hit: 'Xit',
      empty: 'Bunday taom topilmadi',
      emptySub: 'Nomni boshqacha yozib ko’ring yoki filtrni olib tashlang',
      emptyCta: 'Filtrni tozalash',
      filters: {
        all: 'Hammasi',
        hit: 'Xit',
        available: 'Mavjud',
        cheap: '{amount} mingdan arzon',
      },
    },
    sheet: {
      close: 'Yopish',
      portion: 'Ulush',
      portions: { one: 'Bir kishilik', large: 'Kattalashtirilgan', two: 'Ikki kishilik tovoq' },
      addons: "Qo'shimchalar",
      addonsMax: 'Xohlagancha tanlang',
      note: 'Oshpazga izoh',
      notePlaceholder: 'Masalan: kam tuzli, achchiq qalampirsiz',
      add: "Savatga qo'shish",
      often: 'Odatda shu bilan buyurtma qiladilar',
      addonList: {
        qazi: "Qo'shimcha qazi",
        egg: 'Bedana tuxumi',
        salad: 'Achichuk salat',
        bread: 'Tandir non',
      },
      added: 'savatga qo’shildi',
    },
    cart: {
      /* A live restaurant with no branch published — which is not the same
         as a failed read, and no longer draws the design's five venues. */
      noVenues: 'Bu restoran hali onlayn buyurtma qabul qilmaydi',
      noVenuesSub:
        "Buyurtma berish uchun filial hali ochilmagan. Restoranga qo'ng'iroq qiling yoki keyinroq qayting.",
      service: 'Xizmat haqi {percent}%',
      rounding: 'Naqdga yaxlitlash',
      cash: 'Naqd',
      card: 'Karta',
      clickSub: 'Ilova orqali',
      paymeSub: 'QR yoki ilova',
      cashSub: 'Kuryerga · {step} ga yaxlitlanadi',
      title: 'Savat',
      sub: '{count} pozitsiya · {mode}',
      empty: "Savat bo'sh",
      emptySub: "Menyudan taom tanlang — narxlar QQS bilan ko'rsatilgan",
      addMore: "Yana taom qo'shish",
      how: 'Qanday olasiz',
      delivery: 'Yetkazish',
      pickup: 'Olib ketish',
      address: 'Manzil',
      flat: 'Xonadon',
      when: 'Qachon',
      phone: 'Telefon',
      asap: 'Imkon qadar tez · {range} daqiqa',
      /* The same choice, without a window — a venue that has published no
         delivery estimate must not have one quoted for it. */
      asapPlain: 'Imkon qadar tez',
      payment: "To'lov",
      summary: 'Buyurtma',
      promo: 'Promokod',
      promoApply: "Qo'llash",
      promoOk: '{code} · {percent}% chegirma qo’llanildi',
      promoBad: 'Kod topilmadi. {code} ni sinab ko’ring.',
      items: 'Taomlar',
      discount: 'Chegirma {code}',
      total: 'Jami',
      free: 'bepul',
      vatNote: 'Shundan QQS {percent}% · {amount} so’m',
      cashNote: 'naqd to’lovda {amount} ga yaxlitlanadi',
      feeFree: 'Yetkazish bepul · buyurtma {amount} so’mdan yuqori',
      feePaid: 'Yetkazish {fee} so’m · {left} so’m qo’shsangiz bepul bo’ladi',
      place: 'Buyurtmani tasdiqlash',
      placeNote:
        'Tasdiqlagandan keyin oshxona 2 daqiqada javob beradi. Shundan keyin bekor qilinmaydi.',
      placed: 'Buyurtma yuborildi · oshxona tasdig’i kutilmoqda',
      readyIn: '{minutes} daq',
    },
    track: {
      title: 'Buyurtma',
      sub: '{address} · kuryer {courier}',
      pending: 'kutilmoqda',
      about: 'Taxminan {minutes} daqiqa',
      delivered: 'Yetkazildi',
      order: 'Tarkibi',
      total: 'Jami',
      paid: "To'landi · {rail} · shundan QQS {percent}% {amount}",
      call: "Qo'ng'iroq",
      advance: 'Namoyish: keyingi holat',
      courierMeta: 'Moped · {distance} km qoldi · {rating} baho',
      steps: {
        received: 'Qabul qilindi',
        confirmed: 'Oshxona tasdiqladi',
        cooking: 'Tayyorlanmoqda',
        courier: "Kuryer yo'lda",
        delivered: 'Yetkazildi',
      },
      none: 'Kuzatiladigan buyurtma yo’q',
      noneSub: 'Buyurtma bergandan keyin uning holati shu yerda ko’rinadi.',
    },
    book: {
      title: 'Stol bandlash',
      body: "Bandlov bepul. Belgilangan vaqtdan 15 daqiqa saqlanadi — kechiksangiz qo'ng'iroq qiling, saqlab turamiz.",
      branch: 'Filial',
      day: 'Kun',
      time: 'Vaqt',
      guests: 'Mehmon soni',
      guestsNote: 'Zalda yoki ayvonda',
      guestsMany: "{max} kishidan yuqori · menejer qo'ng'iroq qiladi",
      name: 'Ism',
      phone: 'Telefon',
      note: 'Izoh',
      notePlaceholder: "Masalan: ayvonda, tug'ilgan kun",
      summary: 'Bandlov',
      date: 'Sana',
      cta: 'Bandlashni tasdiqlash',
      ctaNote: 'SMS keladi. Bekor qilish uchun shu SMS ga javob yozing.',
      done: 'Bandlov yuborildi · SMS bilan tasdiqlanadi',
      taken: '{time} band · boshqa vaqtni tanlang',
      noSlots: "Bu kunga bo'sh vaqt qolmadi — boshqa kunni tanlang",
      code: 'Bandlov kodi',
      codeNote: 'Kodni saqlang — bandlovni shu kod bilan bekor qilasiz.',
      manage: 'Sizning bandlovingiz',
      pending: 'Tasdiq kutilmoqda',
      confirm: 'Ha, kelamiz',
      confirmed: 'Bandlov tasdiqlandi',
      cancel: 'Bandlovni bekor qilish',
      cancelled: "Bandlov bekor qilindi · stol bo'shatildi",
    },
    about: {
      title: 'Biz haqimizda',
      body: "Osh Xona 2014 yilda Chilonzorda bitta qozon bilan ochildi. Bugun besh filial, lekin osh baribir bitta oshpaz qo'lida damlanadi va go'sht har kuni bozordan olinadi.",
      faq: "Ko'p beriladigan savollar",
      unwritten: '{name}: menyu, buyurtma va stol bandlash shu saytda.',
      cards: [
        {
          head: 'Bitta qozon, bitta oshpaz',
          body: 'Oshni 2014 yildan buyon Rustam aka damlaydi. Retsept o’zgarmagan.',
        },
        {
          head: 'Zal, ayvon va xona',
          body: '120 o’rin. Ayvon bahordan kuzgacha ochiq, xona 12 kishiga.',
        },
        {
          head: 'Har kuni bozorga',
          body: '06:00 da Chorsuga chiqamiz. Go’sht muzlatilmaydi, sabzavot o’sha kuni keladi.',
        },
      ],
      questions: [
        {
          q: 'Yetkazish qancha vaqt oladi?',
          a: 'Toshkent bo’ylab 25–40 daqiqa. Band soatlarda (19:00–21:00) 15 daqiqagacha uzayadi — buyurtma berganda aniq vaqt ko’rsatiladi.',
        },
        {
          q: 'Yetkazish bepulmi?',
          a: '150 000 so’mdan yuqori buyurtmalar bepul yetkaziladi. Undan pastda 15 000 so’m.',
        },
        {
          q: 'Narxda QQS bormi?',
          a: 'Ha. Menyudagi narx — siz to’laydigan yakuniy narx, QQS 12% uning ichida. Chekda alohida qator bilan ko’rsatiladi.',
        },
        {
          q: 'Stolni qanday bandlayman?',
          a: 'Saytdagi bandlash bo’limidan yoki filial telefoniga qo’ng’iroq qilib. Bandlov 15 daqiqa saqlanadi.',
        },
        {
          q: 'Buyurtmani bekor qila olamanmi?',
          a: 'Oshxona tasdiqlaganidan keyin bekor qilinmaydi — taom tayyorlanishga kirgan bo’ladi. Undan oldin telefon orqali bekor qilish mumkin.',
        },
      ],
      contact: 'Aloqa',
    },
    footer: {
      app: 'Ilovani o‘rnating',
      appleOver: 'Yuklab olish',
      apple: 'App Store',
      appleNote: 'App Store’da hali yo’q · iPhone’da saytdan o’rnatiladi',
      googleOver: 'Olish',
      google: 'Google Play',
      googleNote: 'To’g’ridan-to’g’ri saytdan',
      googleNone: 'Android fayli hali nashr qilinmagan',
      about:
        "Toshkentda beshta filial. Osh, kabob va tandir non — 2014 yildan buyon o'sha retsept bo'yicha.",
      branches: 'Filiallar',
      menu: 'Menyu',
      contact: 'Aloqa',
      hours: 'Har kuni {from} – {to}',
      rights: '© {year} {name} · Barcha huquqlar himoyalangan',
      powered: 'Smart Restaurant Cloud da ishlaydi',
    },
    common: {
      som: "so'm",
      offline: 'Menyu namunaviy — server javob bermadi',
      menuUnwritten: 'Menyu hali kiritilmagan — tez orada.',
    },
  },
};

export type GuestCopy = typeof uz;

const ru: GuestCopy = {
  qr: {
    scan: {
      branch: 'Филиал {name}',
      table: 'Ваш стол · {table}',
      tableMeta: 'Официант {waiter} · {guests} гостя',
      openMenu: 'Посмотреть меню',
      openMenuSub: '{count} блюда · цены с НДС',
      callWaiter: 'Позвать официанта',
      callWaiterSub: 'Средний ответ 40 секунд',
      payBill: 'Оплатить счёт',
      payBillSub: 'Карта, Click или Payme',
      noApp:
        'Приложение скачивать не нужно. Регистрация не требуется — заказ привязан к номеру стола.',
      wifi: 'Wi-Fi: {network} · без пароля',
    },
    menu: {
      title: 'Меню',
      count: '{count} блюд',
      countFor: '{count} блюд · «{query}»',
      search: 'Поиск',
      searchPlaceholder: 'Поиск блюда',
      clear: 'Очистить поиск',
      all: 'Всё',
      veg: 'VEG',
      hot: 'ОСТРО',
      soldOut: 'ЗАКОНЧИЛОСЬ',
      soldOutNote: 'На сегодня закончилось. Завтра вернётся.',
      empty: 'Блюдо не найдено',
      emptySub: 'Введите другое название или выберите категорию.',
      showAll: 'Показать всё',
      viewOrder: 'Посмотреть заказ',
      added: '{name} · добавлено в корзину',
      addedMany: '{count} × {name} · добавлено в корзину',
    },
    dish: {
      back: 'Вернуться в меню',
      ingredients: 'Состав',
      allergens: 'Аллергены',
      addons: 'Добавки',
      optional: 'необязательно',
      note: 'Комментарий на кухню',
      notePlaceholder: 'Например: без лука',
      add: 'Добавить ·',
      decrease: 'Убавить',
      increase: 'Прибавить',
      noAllergens: 'Аллергенов нет.',
      addonList: {
        meat: 'Дополнительное мясо',
        qazi: 'Казы',
        egg: 'Перепелиное яйцо',
        noFat: 'Без курдючного жира',
      },
    },
    status: {
      title: 'Статус заказа',
      order: 'Заказ № {number}',
      lines: '{count} позиций',
      cooking: 'Готовится',
      about: 'Примерно',
      minutes: 'минут',
      readyBy: 'Будет готово: {time}',
      yourOrder: 'Ваш заказ',
      basket: 'Корзина',
      empty: 'Корзина пуста. Добавьте блюдо из меню — оно появится здесь.',
      addMore: 'Добавить к заказу',
      pending: 'ожидается',
      send: 'Отправить на кухню',
      sending: 'Отправляется…',
      sent: 'Отправлено на кухню',
      steps: {
        sent: 'Заказ отправлен',
        accepted: 'Кухня приняла',
        cooking: 'Готовится',
        ready: 'Готово',
        served: 'Подано',
      },
    },
    bill: {
      title: 'Счёт',
      table: 'Стол {table} · {guests} гостя',
      items: 'Блюда',
      service: 'Сервисный сбор {percent}%',
      discount: 'Скидка · Золотая карта {percent}%',
      total: 'Итого',
      vat: 'в том числе НДС {percent}%',
      split: 'Разделить счёт',
      splitSub: 'Делится ровно. Разница от округления идёт в первый чек.',
      splitWays: 'гостей',
      splitEach: 'Каждому',
      splitFirst: 'Первый чек',
      railApp: 'Откроется приложение',
      railWaiter: 'Официант будет вызван',
      splitNote: 'Каждый гость платит свою долю отдельно. Официанта звать не нужно.',
      close: 'Закрыть',
      howPay: 'Как оплатите',
      tip: 'Чай',
      tipNote: 'полностью официанту',
      tipNone: 'Нет',
      noTip: 'Чай не добавлен',
      pay: 'Позвать официанта · счёт',
      cashRounded: 'при оплате наличными округляем до {amount}',
    },
    rating: {
      paid: 'Оплата принята',
      paidLine: '{amount} {currency} · {method} · чек на soliq.uz',
      receipt: 'Нужен чек?',
      receiptDone: 'Попросите чек на кассе — пока только бумажный',
      title: 'Как всё прошло?',
      sub: 'Оценку видят официант и менеджер',
      whatGood: 'Что было хорошо?',
      commentPlaceholder: 'Если хотите, напишите подробнее',
      loyalty: 'Сохранить мой номер, чтобы получить {percent}% скидки в следующий раз',
      send: 'Отправить оценку',
      skip: 'Позже',
      skipped: 'Оценка пропущена',
      thanks: 'Спасибо · {stars}★ · отправлено менеджеру',
      stars: ['Было плохо', 'Так себе', 'Нормально', 'Очень хорошо', 'Отлично'],
      tags: [
        'Вкусная еда',
        'Быстро подали',
        'Внимательный официант',
        'Чисто',
        'Цена оправдана',
        'Тихо и спокойно',
      ],
    },
    scanner: {
      title: 'Столовый QR-код',
      body: 'Наведите камеру на код — меню откроется само.',
      allowTitle: 'Камера ещё не включена',
      allowBody:
        'Чтобы прочитать код, нужна камера. Снимок не сохраняется и никуда не отправляется — приложение читает только адрес внутри кода.',
      allow: 'Включить камеру',
      deniedTitle: 'Доступ к камере закрыт',
      deniedBody:
        'Разрешение отключено в настройках телефона, поэтому приложение не может спросить снова. Включите его в настройках или спросите номер стола у официанта.',
      settings: 'Открыть настройки',
      wrongTitle: 'Это не код стола',
      wrongBody: 'Прочитанный код ведёт на другой адрес. Отсканируйте код на столе ещё раз.',
      again: 'Сканировать снова',
    },
    common: {
      waiterCalled: 'Официант вызван',
      waiterOnWay: '{waiter} идёт',
      demoPayment: 'Демо-режим · платёж не отправлен',
      loyaltyOn: 'Скидка золотой карты применена · {percent}%',
      loyaltyOff: 'Скидка убрана',
      offline: 'Меню демонстрационное — сервер не ответил',
      menuUnwritten: 'Меню ещё не заполнено — скоро.',
      retry: 'Повторить',
    },
  },

  site: {
    nav: {
      home: 'Главная',
      menu: 'Меню',
      book: 'Бронь стола',
      track: 'Отслеживание',
      about: 'О нас',
      cart: 'Корзина',
      theme: 'Светлая и тёмная тема',
      tagline: 'Ташкент · {count} филиалов',
    },
    home: {
      openNow: 'Сейчас открыто · до {until}',
      closedNow: 'Сейчас закрыто',
      title: 'Место, где говорят за пловом',
      body: 'Ташкентский плов с казы, шашлык на углях и тандырная лепёшка, которую печём трижды в день. Доставим или встретим.',
      ratings: '· {count} оценок',
      eta: 'Доставка {range} минут',
      freeFrom: 'Бесплатно от {amount} сум',
      ctaOrder: 'Открыть меню',
      ctaBook: 'Забронировать стол',
      popular: 'Заказывают чаще всего',
      popularSub: 'За последние 30 дней',
      seeAll: 'Всё меню',
      branches: 'Филиалы',
      branchesSub: 'Выберите ближайший для самовывоза и брони',
      open: 'Открыт',
      closed: 'Закрыт',
      mostOrdered: 'Заказывают чаще всего',
      quick: {
        delivery: 'Доставка',
        deliverySub: '{range} минут, от {amount} сум бесплатно',
        pickup: 'Самовывоз',
        pickupSub: 'Готово за {minutes} минут, без сервисного сбора',
        book: 'Бронь стола',
        bookSub: 'Зал, терраса или кабинет — бесплатно',
        large: 'Большой заказ',
        largeSub: 'Для свадеб и банкетов · от {people} человек',
        largeToast: 'Для большого заказа звоните {phone}',
      },
      promises: [
        {
          value: '12',
          head: 'лет на одном месте',
          body: 'С 2014 года в Чиланзаре. Тот же повар, тот же казан.',
        },
        {
          value: '06:00',
          head: 'выезжаем на базар',
          body: 'Мясо и овощи покупаем каждый день, замороженное не используем.',
        },
        {
          value: '4.9',
          head: 'средняя оценка',
          body: 'На основе 1 240 оценок. Каждый отзыв читаем и отвечаем.',
        },
      ],
      popularAny: 'Выбрано из меню',
      baked: 'Печём трижды в день',
      orders: '· {count} заказов',
    },
    menu: {
      title: 'Меню',
      sub: '{count} позиций · цены с НДС · обновляются ежедневно',
      found: 'Найдено блюд: {count}',
      search: 'Поиск по названию блюда',
      add: 'Добавить',
      soldOut: 'Закончилось',
      soldOutToast: 'Это блюдо на сегодня закончилось',
      hit: 'Хит',
      empty: 'Такое блюдо не найдено',
      emptySub: 'Попробуйте написать иначе или снять фильтр',
      emptyCta: 'Сбросить фильтр',
      filters: {
        all: 'Все',
        hit: 'Хит',
        available: 'В наличии',
        cheap: 'До {amount} тысяч',
      },
    },
    sheet: {
      close: 'Закрыть',
      portion: 'Порция',
      portions: { one: 'На одного', large: 'Увеличенная', two: 'Блюдо на двоих' },
      addons: 'Добавки',
      addonsMax: 'Выбирайте сколько нужно',
      note: 'Комментарий повару',
      notePlaceholder: 'Например: меньше соли, без острого перца',
      add: 'В корзину',
      often: 'Обычно заказывают вместе',
      addonList: {
        qazi: 'Дополнительно казы',
        egg: 'Яйцо перепелиное',
        salad: 'Салат ачичук',
        bread: 'Тандырная лепёшка',
      },
      added: 'добавлено в корзину',
    },
    cart: {
      /* A live restaurant with no branch published — which is not the same
         as a failed read, and no longer draws the design's five venues. */
      noVenues: 'Этот ресторан пока не принимает онлайн-заказы',
      noVenuesSub:
        'Ни один филиал ещё не открыт для заказов. Позвоните в ресторан или зайдите позже.',
      service: 'Сервисный сбор {percent}%',
      rounding: 'Округление для наличных',
      cash: 'Наличные',
      card: 'Карта',
      clickSub: 'Через приложение',
      paymeSub: 'QR или приложение',
      cashSub: 'Курьеру · округляем до {step}',
      title: 'Корзина',
      sub: '{count} позиций · {mode}',
      empty: 'Корзина пуста',
      emptySub: 'Выберите блюда из меню — цены указаны с НДС',
      addMore: 'Добавить ещё блюдо',
      how: 'Как получите',
      delivery: 'Доставка',
      pickup: 'Самовывоз',
      address: 'Адрес',
      flat: 'Квартира',
      when: 'Когда',
      phone: 'Телефон',
      asap: 'Как можно скорее · {range} минут',
      /* The same choice, without a window — a venue that has published no
         delivery estimate must not have one quoted for it. */
      asapPlain: 'Как можно скорее',
      payment: 'Оплата',
      summary: 'Заказ',
      promo: 'Промокод',
      promoApply: 'Применить',
      promoOk: '{code} · скидка {percent}% применена',
      promoBad: 'Код не найден. Попробуйте {code}.',
      items: 'Блюда',
      discount: 'Скидка {code}',
      total: 'Итого',
      free: 'бесплатно',
      vatNote: 'В том числе НДС {percent}% · {amount} сум',
      cashNote: 'при оплате наличными округляем до {amount}',
      feeFree: 'Доставка бесплатно · заказ свыше {amount} сум',
      feePaid: 'Доставка {fee} сум · ещё {left} сум до бесплатной',
      place: 'Оформить заказ',
      placeNote: 'После оформления кухня ответит за 2 минуты. После этого отменить нельзя.',
      placed: 'Заказ отправлен · ожидаем подтверждения кухни',
      readyIn: '{minutes} мин',
    },
    track: {
      title: 'Заказ',
      sub: '{address} · курьер {courier}',
      pending: 'ожидается',
      about: 'Примерно {minutes} минут',
      delivered: 'Доставлено',
      order: 'Состав',
      total: 'Итого',
      paid: 'Оплачено · {rail} · в том числе НДС {percent}% {amount}',
      call: 'Позвонить',
      advance: 'Демо: следующий статус',
      courierMeta: 'Мопед · осталось {distance} км · оценка {rating}',
      steps: {
        received: 'Заказ принят',
        confirmed: 'Кухня подтвердила',
        cooking: 'Готовится',
        courier: 'Курьер в пути',
        delivered: 'Доставлено',
      },
      none: 'Нет заказа для отслеживания',
      noneSub: 'После оформления заказа его статус появится здесь.',
    },
    book: {
      title: 'Бронь стола',
      body: 'Бронь бесплатна. Держим 15 минут после назначенного времени — если опаздываете, позвоните, сохраним.',
      branch: 'Филиал',
      day: 'День',
      time: 'Время',
      guests: 'Число гостей',
      guestsNote: 'В зале или на террасе',
      guestsMany: 'Свыше {max} человек · менеджер перезвонит',
      name: 'Имя',
      phone: 'Телефон',
      note: 'Комментарий',
      notePlaceholder: 'Например: на террасе, день рождения',
      summary: 'Бронь',
      date: 'Дата',
      cta: 'Подтвердить бронь',
      ctaNote: 'Придёт SMS. Для отмены ответьте на это SMS.',
      done: 'Бронь отправлена · подтвердим по SMS',
      taken: '{time} занято · выберите другое время',
      noSlots: 'На этот день свободного времени не осталось — выберите другой',
      code: 'Код брони',
      codeNote: 'Сохраните код — по нему бронь можно отменить.',
      manage: 'Ваша бронь',
      pending: 'Ожидает подтверждения',
      confirm: 'Да, придём',
      confirmed: 'Бронь подтверждена',
      cancel: 'Отменить бронь',
      cancelled: 'Бронь отменена · столик освобождён',
    },
    about: {
      title: 'О нас',
      body: 'Osh Xona открылась в 2014 году в Чиланзаре с одним казаном. Сегодня пять филиалов, но плов по-прежнему готовит один повар, а мясо покупаем на базаре каждый день.',
      faq: 'Частые вопросы',
      unwritten: '{name}: меню, заказ и бронь стола — на этом сайте.',
      cards: [
        {
          head: 'Один казан, один повар',
          body: 'Плов с 2014 года готовит Рустам-ака. Рецепт не менялся.',
        },
        {
          head: 'Зал, терраса и кабинет',
          body: '120 мест. Терраса открыта с весны до осени, кабинет на 12 человек.',
        },
        {
          head: 'Каждый день на базар',
          body: 'В 06:00 выезжаем на Чорсу. Мясо не морозим, овощи привозим в тот же день.',
        },
      ],
      questions: [
        {
          q: 'Сколько занимает доставка?',
          a: 'По Ташкенту 25–40 минут. В часы пик (19:00–21:00) дольше на 15 минут — точное время видно при заказе.',
        },
        {
          q: 'Доставка бесплатная?',
          a: 'Заказы свыше 150 000 сум доставляем бесплатно. Ниже — 15 000 сум.',
        },
        {
          q: 'НДС включён в цену?',
          a: 'Да. Цена в меню — итоговая, НДС 12% уже включён. В чеке он показан отдельной строкой.',
        },
        {
          q: 'Как забронировать стол?',
          a: 'Через раздел бронирования или по телефону филиала. Бронь держим 15 минут.',
        },
        {
          q: 'Можно ли отменить заказ?',
          a: 'После подтверждения кухней — нет, блюдо уже в работе. До этого можно отменить по телефону.',
        },
      ],
      contact: 'Контакты',
    },
    footer: {
      app: 'Установите приложение',
      appleOver: 'Скачать в',
      apple: 'App Store',
      appleNote: 'В App Store пока нет · на iPhone ставится с сайта',
      googleOver: 'Доступно в',
      google: 'Google Play',
      googleNote: 'Напрямую с сайта',
      googleNone: 'Файл для Android ещё не опубликован',
      about:
        'Пять филиалов в Ташкенте. Плов, шашлык и тандырная лепёшка — по тому же рецепту с 2014 года.',
      branches: 'Филиалы',
      menu: 'Меню',
      contact: 'Контакты',
      hours: 'Ежедневно {from} – {to}',
      rights: '© {year} {name} · Все права защищены',
      powered: 'Работает на Smart Restaurant Cloud',
    },
    common: {
      som: 'сум',
      offline: 'Меню демонстрационное — сервер не ответил',
      menuUnwritten: 'Меню ещё не заполнено — скоро.',
    },
  },
};

const en: GuestCopy = {
  qr: {
    scan: {
      branch: '{name} branch',
      table: 'Your table · {table}',
      tableMeta: 'Waiter {waiter} · {guests} guests',
      openMenu: 'Open the menu',
      openMenuSub: '{count} dishes · prices include VAT',
      callWaiter: 'Call the waiter',
      callWaiterSub: 'Average response 40 seconds',
      payBill: 'Pay the bill',
      payBillSub: 'Card, Click or Payme',
      noApp: 'No app to download. No signup either — the order is tied to the table number.',
      wifi: 'Wi-Fi: {network} · no password',
    },
    menu: {
      title: 'Menu',
      count: '{count} dishes',
      countFor: '{count} dishes · “{query}”',
      search: 'Search',
      searchPlaceholder: 'Search dishes',
      clear: 'Clear the search',
      all: 'All',
      veg: 'VEG',
      hot: 'SPICY',
      soldOut: 'SOLD OUT',
      soldOutNote: 'Sold out today. Back tomorrow.',
      empty: 'No dish found',
      emptySub: 'Try another name, or pick a category.',
      showAll: 'Show everything',
      viewOrder: 'View order',
      added: '{name} · added to the order',
      addedMany: '{count} × {name} · added to the order',
    },
    dish: {
      back: 'Back to the menu',
      ingredients: 'Ingredients',
      allergens: 'Allergens',
      addons: 'Add-ons',
      optional: 'optional',
      note: 'Note to the kitchen',
      notePlaceholder: 'For example: no onion',
      add: 'Add ·',
      decrease: 'One fewer',
      increase: 'One more',
      noAllergens: 'No allergens.',
      addonList: {
        meat: 'Extra meat',
        qazi: 'Qazi',
        egg: 'Quail egg',
        noFat: 'No tail fat',
      },
    },
    status: {
      title: 'Order status',
      order: 'Order № {number}',
      lines: '{count} items',
      cooking: 'Cooking',
      about: 'About',
      minutes: 'minutes',
      readyBy: 'Ready by: {time}',
      yourOrder: 'Your order',
      basket: 'Basket',
      empty: 'The order is empty. Add a dish from the menu and it appears here.',
      addMore: 'Add to the order',
      pending: 'pending',
      send: 'Send to the kitchen',
      sending: 'Sending…',
      sent: 'Sent to the kitchen',
      steps: {
        sent: 'Order sent',
        accepted: 'Kitchen accepted',
        cooking: 'Cooking',
        ready: 'Ready',
        served: 'Served',
      },
    },
    bill: {
      title: 'Bill',
      table: 'Table {table} · {guests} guests',
      items: 'Items',
      service: 'Service charge {percent}%',
      discount: 'Discount · Gold card {percent}%',
      total: 'Total',
      vat: 'of which VAT {percent}%',
      split: 'Split the bill',
      splitSub: 'Split evenly. The rounding difference goes onto the first share.',
      splitWays: 'guests',
      splitEach: 'Each share',
      splitFirst: 'First share',
      railApp: 'Opens the app',
      railWaiter: 'The waiter will be called',
      splitNote: 'Each guest pays their own share. No need to call the waiter.',
      close: 'Close',
      howPay: 'How will you pay',
      tip: 'Tip',
      tipNote: 'goes fully to the waiter',
      tipNone: 'None',
      noTip: 'No tip added',
      pay: 'Call the waiter · bill',
      cashRounded: 'paying cash rounds to {amount}',
    },
    rating: {
      paid: 'Payment received',
      paidLine: '{amount} {currency} · {method} · receipt on soliq.uz',
      receipt: 'Need a receipt?',
      receiptDone: 'Ask at the till — paper only for now',
      title: 'How was it today?',
      sub: 'The waiter and the manager see your rating',
      whatGood: 'What went well?',
      commentPlaceholder: 'Add a comment if you like',
      loyalty: 'Save my number for a {percent}% discount on my next visit',
      send: 'Send rating',
      skip: 'Later',
      skipped: 'Rating skipped',
      thanks: 'Thank you · {stars}★ · sent to the manager',
      stars: ['Not good', 'Below average', 'Fine', 'Very good', 'Excellent'],
      tags: [
        'Great food',
        'Served fast',
        'Attentive waiter',
        'Clean',
        'Good value',
        'Calm and quiet',
      ],
    },
    scanner: {
      title: 'The QR code on your table',
      body: 'Hold the code inside the frame — the menu opens by itself.',
      allowTitle: 'The camera is not on yet',
      allowBody:
        'Reading the code needs the camera. Nothing is stored and nothing is sent — the app only reads the address inside the code.',
      allow: 'Turn the camera on',
      deniedTitle: 'Camera access is blocked',
      deniedBody:
        'The permission is switched off in the phone’s settings, so the app cannot ask again. Turn it on there, or ask the waiter for your table number.',
      settings: 'Open settings',
      wrongTitle: 'That is not a table code',
      wrongBody: 'The code points somewhere else. Scan the code on the table again.',
      again: 'Scan again',
    },
    common: {
      waiterCalled: 'Waiter called',
      waiterOnWay: '{waiter} is on the way',
      demoPayment: 'Demo mode · no payment sent',
      loyaltyOn: 'Gold card discount applied · {percent}%',
      loyaltyOff: 'Discount removed',
      offline: 'Showing a sample menu — the server did not answer',
      menuUnwritten: 'The menu is not written yet — soon.',
      retry: 'Try again',
    },
  },

  site: {
    nav: {
      home: 'Home',
      menu: 'Menu',
      book: 'Book a table',
      track: 'Track order',
      about: 'About',
      cart: 'Cart',
      theme: 'Light and dark theme',
      tagline: 'Tashkent · {count} branches',
    },
    home: {
      openNow: 'Open now · until {until}',
      closedNow: 'Closed now',
      title: 'The place where talk happens over plov',
      body: 'Tashkent plov with qazi, charcoal kebab, and tandoor bread baked three times a day. We deliver, or we will meet you at the door.',
      ratings: '· {count} ratings',
      eta: 'Delivery {range} min',
      freeFrom: 'Free from {amount} so’m',
      ctaOrder: 'Open the menu',
      ctaBook: 'Book a table',
      popular: 'Ordered most often',
      popularSub: 'Over the last 30 days',
      seeAll: 'Full menu',
      branches: 'Branches',
      branchesSub: 'Pick the nearest one for pickup or a booking',
      open: 'Open',
      closed: 'Closed',
      mostOrdered: 'Most ordered',
      quick: {
        delivery: 'Delivery',
        deliverySub: '{range} min, free from {amount}',
        pickup: 'Pickup',
        pickupSub: 'Ready in {minutes} min, no service charge',
        book: 'Book a table',
        bookSub: 'Hall, terrace or private room — free',
        large: 'Large order',
        largeSub: 'For weddings and events · {people} people up',
        largeToast: 'For large orders call {phone}',
      },
      promises: [
        {
          value: '12',
          head: 'years in one place',
          body: 'In Chilonzor since 2014. Same cook, same kazan.',
        },
        {
          value: '06:00',
          head: 'we leave for the market',
          body: 'Meat and vegetables bought fresh daily; nothing frozen.',
        },
        {
          value: '4.9',
          head: 'average rating',
          body: 'From 1 240 guest ratings. Every review is read and answered.',
        },
      ],
      popularAny: 'Picked from the menu',
      baked: 'Baked 3× a day',
      orders: '· {count} orders',
    },
    menu: {
      title: 'Menu',
      sub: '{count} items · prices include VAT · updated daily',
      found: '{count} dishes found',
      search: 'Search by dish name',
      add: 'Add',
      soldOut: 'Sold out',
      soldOutToast: 'This dish has sold out for today',
      hit: 'Popular',
      empty: 'No dish matches that',
      emptySub: 'Try another spelling, or clear the filter',
      emptyCta: 'Clear the filter',
      filters: {
        all: 'All',
        hit: 'Popular',
        available: 'Available',
        cheap: 'Under {amount} thousand',
      },
    },
    sheet: {
      close: 'Close',
      portion: 'Portion',
      portions: { one: 'One person', large: 'Larger', two: 'Dish for two' },
      addons: 'Add-ons',
      addonsMax: 'Pick as many as you like',
      note: 'Note for the kitchen',
      notePlaceholder: 'For example: less salt, no hot pepper',
      add: 'Add to cart',
      often: 'Usually ordered together',
      addonList: {
        qazi: 'Extra qazi',
        egg: 'Quail egg',
        salad: 'Achichuk salad',
        bread: 'Tandoor bread',
      },
      added: 'added to the cart',
    },
    cart: {
      /* A live restaurant with no branch published — which is not the same
         as a failed read, and no longer draws the design's five venues. */
      noVenues: 'This restaurant is not taking online orders yet',
      noVenuesSub: 'No branch is open for ordering yet. Call the restaurant, or come back later.',
      service: 'Service charge {percent}%',
      rounding: 'Cash rounding',
      cash: 'Cash',
      card: 'Card',
      clickSub: 'Through the app',
      paymeSub: 'QR or app',
      cashSub: 'To the courier · rounded to {step}',
      title: 'Cart',
      sub: '{count} items · {mode}',
      empty: 'The cart is empty',
      emptySub: 'Pick something from the menu — prices include VAT',
      addMore: 'Add another dish',
      how: 'How you will get it',
      delivery: 'Delivery',
      pickup: 'Pickup',
      address: 'Address',
      flat: 'Flat',
      when: 'When',
      phone: 'Phone',
      asap: 'As soon as possible · {range} min',
      /* The same choice, without a window — a venue that has published no
         delivery estimate must not have one quoted for it. */
      asapPlain: 'As soon as possible',
      payment: 'Payment',
      summary: 'Your order',
      promo: 'Promo code',
      promoApply: 'Apply',
      promoOk: '{code} · {percent}% discount applied',
      promoBad: 'Code not found. Try {code}.',
      items: 'Items',
      discount: 'Discount {code}',
      total: 'Total',
      free: 'free',
      vatNote: 'Of which VAT {percent}% · {amount} so’m',
      cashNote: 'paying cash rounds to {amount}',
      feeFree: 'Delivery is free · order above {amount} so’m',
      feePaid: 'Delivery {fee} so’m · {left} so’m more and it is free',
      place: 'Place the order',
      placeNote: 'The kitchen answers within 2 minutes. After that the order cannot be cancelled.',
      placed: 'Order sent · waiting for the kitchen to confirm',
      readyIn: '{minutes} min',
    },
    track: {
      title: 'Order',
      sub: '{address} · courier {courier}',
      pending: 'pending',
      about: 'About {minutes} minutes',
      delivered: 'Delivered',
      order: 'What is in it',
      total: 'Total',
      paid: 'Paid · {rail} · of which VAT {percent}% {amount}',
      call: 'Call',
      advance: 'Demo: next status',
      courierMeta: 'Moped · {distance} km to go · {rating} rating',
      steps: {
        received: 'Order received',
        confirmed: 'Kitchen confirmed',
        cooking: 'Cooking',
        courier: 'Courier on the way',
        delivered: 'Delivered',
      },
      none: 'No order to track',
      noneSub: 'Once you place an order, its status shows up here.',
    },
    book: {
      title: 'Book a table',
      body: 'Booking is free. We hold the table for 15 minutes past your time — call if you are late and we will keep it.',
      branch: 'Branch',
      day: 'Day',
      time: 'Time',
      guests: 'Guests',
      guestsNote: 'In the hall or on the terrace',
      guestsMany: 'Above {max} people · the manager will call',
      name: 'Name',
      phone: 'Phone',
      note: 'Note',
      notePlaceholder: 'For example: on the terrace, a birthday',
      summary: 'Booking',
      date: 'Date',
      cta: 'Confirm the booking',
      ctaNote: 'You will get an SMS. Reply to it to cancel.',
      done: 'Booking sent · we will confirm by SMS',
      taken: '{time} is taken · pick another time',
      noSlots: 'No times left for this day — pick another',
      code: 'Booking code',
      codeNote: 'Keep the code — it is how you cancel the booking.',
      manage: 'Your booking',
      pending: 'Waiting for confirmation',
      confirm: 'Yes, we are coming',
      confirmed: 'Booking confirmed',
      cancel: 'Cancel the booking',
      cancelled: 'Booking cancelled · the table is free again',
    },
    about: {
      title: 'About us',
      body: 'Osh Xona opened in Chilonzor in 2014 with a single kazan. There are five branches now, but one cook still makes the plov and the meat is bought at the market every day.',
      faq: 'Common questions',
      unwritten: '{name}: the menu, ordering and table booking live on this site.',
      cards: [
        {
          head: 'One kazan, one cook',
          body: 'Rustam aka has cooked the plov since 2014. The recipe has not changed.',
        },
        {
          head: 'Hall, terrace and private room',
          body: '120 seats. The terrace is open spring to autumn; the room seats 12.',
        },
        {
          head: 'To the market every day',
          body: 'We leave for Chorsu at 06:00. Meat is never frozen; vegetables arrive the same day.',
        },
      ],
      questions: [
        {
          q: 'How long does delivery take?',
          a: '25–40 minutes across Tashkent. In peak hours (19:00–21:00) add up to 15 minutes; the exact time shows at checkout.',
        },
        {
          q: 'Is delivery free?',
          a: 'Orders above 150 000 so’m ship free. Below that it is 15 000 so’m.',
        },
        {
          q: 'Is VAT included?',
          a: 'Yes. The menu price is final and includes 12% VAT, which the receipt shows on its own line.',
        },
        {
          q: 'How do I book a table?',
          a: 'Through the booking section, or by calling the branch. We hold a table for 15 minutes.',
        },
        {
          q: 'Can I cancel an order?',
          a: 'Not once the kitchen confirms it — the dish is already being made. Before that, call to cancel.',
        },
      ],
      contact: 'Contact',
    },
    footer: {
      app: 'Get the app',
      appleOver: 'Download on the',
      apple: 'App Store',
      appleNote: 'Not on the App Store yet · installs from the site on iPhone',
      googleOver: 'Get it on',
      google: 'Google Play',
      googleNote: 'Straight from this site',
      googleNone: 'The Android file is not published yet',
      about:
        'Five branches in Tashkent. Plov, kebab and tandoor bread — the same recipe since 2014.',
      branches: 'Branches',
      menu: 'Menu',
      contact: 'Contact',
      hours: 'Daily {from} – {to}',
      rights: '© {year} {name} · All rights reserved',
      powered: 'Runs on Smart Restaurant Cloud',
    },
    common: {
      som: "so'm",
      offline: 'Showing a sample menu — the server did not answer',
      menuUnwritten: 'The menu is not written yet — soon.',
    },
  },
};

export const guestCopy = { uz, ru, en } as const;

/**
 * The fourteen declarable allergens, by the slug the API stores.
 *
 * `menu_items.allergens` is `["gluten","egg","sesame"]` — slugs, not prose —
 * because a restaurant edits the list in one language and every guest reads it
 * in their own. So the words live here.
 *
 * Kept beside the catalogue rather than inside it because it is keyed by an API
 * value rather than by a screen, and a slug the list does not know falls
 * through to itself: a new allergen appearing as `lupin` is a small ugliness,
 * a blank line under “Allergens” is a health question answered with silence.
 *
 * The list is the EU's fourteen, which is what Uzbek labelling follows.
 */
export const allergenLabels: Record<string, { uz: string; ru: string; en: string }> = {
  gluten: { uz: 'Glyuten', ru: 'Глютен', en: 'Gluten' },
  egg: { uz: 'Tuxum', ru: 'Яйцо', en: 'Egg' },
  dairy: { uz: 'Sut mahsulotlari', ru: 'Молочные продукты', en: 'Dairy' },
  milk: { uz: 'Sut', ru: 'Молоко', en: 'Milk' },
  nuts: { uz: "Yong'oq", ru: 'Орехи', en: 'Tree nuts' },
  peanut: { uz: "Yeryong'oq", ru: 'Арахис', en: 'Peanut' },
  sesame: { uz: 'Kunjut', ru: 'Кунжут', en: 'Sesame' },
  soy: { uz: 'Soya', ru: 'Соя', en: 'Soy' },
  fish: { uz: 'Baliq', ru: 'Рыба', en: 'Fish' },
  shellfish: { uz: 'Qisqichbaqasimonlar', ru: 'Ракообразные', en: 'Crustaceans' },
  molluscs: { uz: 'Mollyuskalar', ru: 'Моллюски', en: 'Molluscs' },
  celery: { uz: 'Selderey', ru: 'Сельдерей', en: 'Celery' },
  mustard: { uz: 'Xantal', ru: 'Горчица', en: 'Mustard' },
  sulphites: { uz: 'Sulfitlar', ru: 'Сульфиты', en: 'Sulphites' },
  lupin: { uz: 'Lyupin', ru: 'Люпин', en: 'Lupin' },
};

/** An allergen slug in the reader's language, or the slug itself. */
export function allergenLabel(slug: string, locale: 'uz' | 'ru' | 'en'): string {
  return allergenLabels[slug]?.[locale] ?? slug;
}
