'use client';

import { useSyncExternalStore } from 'react';

import type { DishImage } from '@restaurant/surfaces/media/image';

/**
 * The basket, for both guest-facing surfaces.
 *
 * A module-level store rather than context, for the same reason the POS offline
 * queue is one: the menu page is server-rendered for the crawler, and wrapping
 * it in a provider would turn every dish row into a client component and put
 * the dish names — the only reason the page is worth indexing — behind
 * JavaScript. Small client islands read this instead.
 *
 * `localStorage`, keyed by whatever the caller calls a basket. The restaurant
 * site passes the slug — a guest who adds three dishes, reads the about page
 * and comes back must find their basket, and one who opens a different
 * restaurant must not find somebody else's. The QR surface passes
 * `slug:table`, because a basket there belongs to a table and not to a phone:
 * two people at table 14 scanning two phones are ordering one order.
 *
 * Prices are integer tiyin and every one of them came from the API. Nothing
 * here multiplies a price by anything except a whole quantity, and the totals
 * shown to a guest are `lib/pricing.ts`'s — which is a transcription of the
 * server's `BillTotals`, kept honest by a test whose expected values were
 * generated by running the PHP.
 */
export type CartLine = {
  /** `dishId` plus a stable hash of the options, so two spellings of the same
   *  dish with different add-ons are two lines and not one. */
  key: string;
  dishId: string;
  name: string;
  /** Tiyin, per unit, add-ons already included. */
  unitPrice: number;
  quantity: number;
  /** Add-on names, already resolved for this reader. Shown under the line. */
  options: readonly string[];
  /**
   * The same choices as the kitchen's own option ids, for the order endpoint.
   *
   * `options` above is what a person reads and `modifierIds` is what
   * `POST /api/v1/public/orders` prices the line by — the two describe one set
   * of taps and neither can do the other's job. A label cannot be sent (the
   * server re-prices through `App\Contracts\Menu\MenuCatalog` and knows nothing
   * about "Katta ulush"), and an id cannot be shown.
   *
   * Optional, and read with `?? []` everywhere, for the reason `image` below is:
   * a basket saved by an earlier build is still in somebody's `localStorage` and
   * must not break because a field was added. A line with none is a dish with no
   * modifier sheet, or one added from a fixture menu — and `placeOrderPayloadFrom`
   * drops any id that is not a number, which is exactly what a fixture carries.
   */
  modifierIds?: readonly string[];
  /** What the guest asked the kitchen for. */
  note: string;
  /**
   * The dish photograph, carried into the basket — one address, the small one.
   * Written by `lineImageFrom`, which is the only place that should decide
   * which size a basket holds.
   *
   * Optional, and read with `?? null` everywhere: a basket saved by an earlier
   * build is still in somebody's `localStorage` and must not blank out because
   * a field was added. `lineKey` deliberately does not include it — the same
   * dish with a new photograph is the same line.
   */
  image?: string | null;
};

/**
 * The one address a basket line carries for its picture.
 *
 * `thumb` — 160px — when the platform holds the set, because every place a
 * line is drawn is a 64px square or smaller and nothing larger is ever shown
 * from a basket. This used to copy `imageUrl`, the largest file the platform
 * has: a four-line basket was four 1600px downloads to paint four thumbnails,
 * and a basket that survives in `localStorage` paid for them again on every
 * visit. The typed-in address is the fallback, because a restaurant whose
 * pictures live elsewhere has exactly one size of each.
 *
 * Takes the two fields by name rather than a `GuestDish`, so the Telegram and
 * marketplace menus — whose dish types carry `image` alone — write the same
 * thing.
 */
export function lineImageFrom(dish: {
  image?: DishImage | null;
  imageUrl?: string | null;
}): string | null {
  const image = dish.image ?? null;

  if (image !== null) return image.sizes.thumb?.url ?? image.src;

  return dish.imageUrl ?? null;
}

export type Cart = {
  /** The basket's own id — a slug, or `slug:table`. */
  restaurant: string;
  lines: readonly CartLine[];
};

const EMPTY: Cart = { restaurant: '', lines: [] };

const keyFor = (restaurant: string) => `srcp.cart.${restaurant}`;

const listeners = new Set<() => void>();

/*
 * The snapshot is cached and only replaced when something actually changes.
 *
 * `useSyncExternalStore` compares snapshots by identity and re-renders whenever
 * they differ. Parsing localStorage on every call would return a new object
 * every time and loop forever — the same trap the POS queue documents.
 */
let cached: Cart = EMPTY;

function read(restaurant: string): Cart {
  if (typeof window === 'undefined') return EMPTY;

  if (cached.restaurant === restaurant) return cached;

  try {
    const raw = window.localStorage.getItem(keyFor(restaurant));
    const parsed = raw === null ? null : (JSON.parse(raw) as { lines?: CartLine[] });

    cached = { restaurant, lines: parsed?.lines ?? [] };
  } catch {
    // A corrupt basket is an empty basket. It is three dishes, not a document.
    cached = { restaurant, lines: [] };
  }

  return cached;
}

function write(next: Cart) {
  cached = next;

  try {
    window.localStorage.setItem(keyFor(next.restaurant), JSON.stringify({ lines: next.lines }));
  } catch {
    /* Private mode, or a full quota. The basket still works for this visit. */
  }

  for (const listener of listeners) listener();
}

function subscribe(listener: () => void): () => void {
  listeners.add(listener);

  /*
   * Another tab counts. A guest with the menu open on a laptop and the basket
   * open in a second tab should see one basket, and `storage` is the only event
   * that fires across them.
   */
  const onStorage = (event: StorageEvent) => {
    if (event.key !== null && event.key.startsWith('srcp.cart.')) {
      cached = EMPTY;
      listener();
    }
  };

  window.addEventListener('storage', onStorage);

  return () => {
    listeners.delete(listener);
    window.removeEventListener('storage', onStorage);
  };
}

/** A stable line key from a dish and the options chosen with it. */
export function lineKey(dishId: string, options: readonly string[], note: string): string {
  return [dishId, [...options].sort().join('|'), note.trim()].join('::');
}

export function useCart(restaurant: string): Cart {
  return useSyncExternalStore(
    subscribe,
    () => read(restaurant),
    () => EMPTY,
  );
}

export function addLine(restaurant: string, line: Omit<CartLine, 'key'>) {
  const current = read(restaurant);
  const key = lineKey(line.dishId, line.options, line.note);
  const existing = current.lines.find((entry) => entry.key === key);

  const lines = existing
    ? current.lines.map((entry) =>
        entry.key === key ? { ...entry, quantity: entry.quantity + line.quantity } : entry,
      )
    : [...current.lines, { ...line, key }];

  write({ restaurant, lines });
}

export function setQuantity(restaurant: string, key: string, quantity: number) {
  const current = read(restaurant);

  write({
    restaurant,
    lines:
      quantity <= 0
        ? current.lines.filter((entry) => entry.key !== key)
        : current.lines.map((entry) => (entry.key === key ? { ...entry, quantity } : entry)),
  });
}

export function clearCart(restaurant: string) {
  write({ restaurant, lines: [] });
}

/** How many things are in the basket, counting quantities. */
export const cartCount = (cart: Cart): number =>
  cart.lines.reduce((sum, line) => sum + line.quantity, 0);

/** What the lines come to, before service, delivery or rounding. */
export const cartSubtotal = (cart: Cart): number =>
  cart.lines.reduce((sum, line) => sum + line.unitPrice * line.quantity, 0);
